import type { Phone } from './types'

export const phones: Phone[] = [
  {
    id: '1',
    name: 'iPhone 15 Pro Max',
    brand: 'Apple',
    price: 1199,
    processor: 'A17 Pro',
    cameraScore: 95,
    batteryScore: 88,
    performanceScore: 98,
    heatingIssue: false,
    longTermScore: 95,
    pros: ['Best-in-class performance', 'Excellent camera system', '5+ years of updates'],
    cons: ['Expensive', 'No expandable storage', 'Slower charging than competitors'],
    imageUrl: '/phones/iphone-15-pro-max.jpg',
    releaseYear: 2023,
    updateYears: 6
  },
  {
    id: '2',
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    price: 1299,
    processor: 'Snapdragon 8 Gen 3',
    cameraScore: 96,
    batteryScore: 90,
    performanceScore: 95,
    heatingIssue: false,
    longTermScore: 90,
    pros: ['200MP camera', 'S Pen included', 'Excellent display'],
    cons: ['Very expensive', 'Heavy and large', 'Can heat under load'],
    imageUrl: '/phones/samsung-s24-ultra.jpg',
    releaseYear: 2024,
    updateYears: 7
  },
  {
    id: '3',
    name: 'Google Pixel 8 Pro',
    brand: 'Google',
    price: 999,
    processor: 'Tensor G3',
    cameraScore: 94,
    batteryScore: 85,
    performanceScore: 85,
    heatingIssue: true,
    longTermScore: 92,
    pros: ['Best AI features', 'Pure Android experience', '7 years of updates'],
    cons: ['Heating issues during gaming', 'Average battery life', 'Limited availability'],
    imageUrl: '/phones/pixel-8-pro.jpg',
    releaseYear: 2023,
    updateYears: 7
  },
  {
    id: '4',
    name: 'OnePlus 12',
    brand: 'OnePlus',
    price: 799,
    processor: 'Snapdragon 8 Gen 3',
    cameraScore: 88,
    batteryScore: 95,
    performanceScore: 94,
    heatingIssue: false,
    longTermScore: 80,
    pros: ['100W fast charging', 'Flagship performance', 'Great value'],
    cons: ['Camera not as refined', 'Fewer software updates', 'No wireless charging on base'],
    imageUrl: '/phones/oneplus-12.jpg',
    releaseYear: 2024,
    updateYears: 4
  },
  {
    id: '5',
    name: 'Samsung Galaxy A54',
    brand: 'Samsung',
    price: 449,
    processor: 'Exynos 1380',
    cameraScore: 78,
    batteryScore: 90,
    performanceScore: 70,
    heatingIssue: false,
    longTermScore: 85,
    pros: ['Great battery life', 'Good display', '4 years of updates'],
    cons: ['Mid-range performance', 'Slower charging', 'Plastic build'],
    imageUrl: '/phones/samsung-a54.jpg',
    releaseYear: 2023,
    updateYears: 4
  },
  {
    id: '6',
    name: 'iPhone 15',
    brand: 'Apple',
    price: 799,
    processor: 'A16 Bionic',
    cameraScore: 88,
    batteryScore: 82,
    performanceScore: 92,
    heatingIssue: false,
    longTermScore: 93,
    pros: ['USB-C finally', 'Reliable performance', 'Great ecosystem'],
    cons: ['60Hz display', 'No always-on display', 'Basic telephoto'],
    imageUrl: '/phones/iphone-15.jpg',
    releaseYear: 2023,
    updateYears: 5
  },
  {
    id: '7',
    name: 'Xiaomi 14 Ultra',
    brand: 'Xiaomi',
    price: 1099,
    processor: 'Snapdragon 8 Gen 3',
    cameraScore: 97,
    batteryScore: 88,
    performanceScore: 93,
    heatingIssue: true,
    longTermScore: 75,
    pros: ['Leica camera system', 'Excellent zoom', 'Fast charging'],
    cons: ['MIUI bloatware', 'Limited updates', 'Can overheat'],
    imageUrl: '/phones/xiaomi-14-ultra.jpg',
    releaseYear: 2024,
    updateYears: 3
  },
  {
    id: '8',
    name: 'Google Pixel 8a',
    brand: 'Google',
    price: 499,
    processor: 'Tensor G3',
    cameraScore: 85,
    batteryScore: 80,
    performanceScore: 80,
    heatingIssue: true,
    longTermScore: 90,
    pros: ['Affordable flagship features', '7 years of updates', 'Great camera'],
    cons: ['Heating issues', 'Smaller battery', 'Slower charging'],
    imageUrl: '/phones/pixel-8a.jpg',
    releaseYear: 2024,
    updateYears: 7
  },
  {
    id: '9',
    name: 'Nothing Phone 2',
    brand: 'Nothing',
    price: 599,
    processor: 'Snapdragon 8+ Gen 1',
    cameraScore: 80,
    batteryScore: 85,
    performanceScore: 82,
    heatingIssue: false,
    longTermScore: 78,
    pros: ['Unique design', 'Clean software', 'Good value'],
    cons: ['Camera could be better', 'Limited availability', 'Unproven long-term'],
    imageUrl: '/phones/nothing-phone-2.jpg',
    releaseYear: 2023,
    updateYears: 3
  },
  {
    id: '10',
    name: 'Samsung Galaxy S23 FE',
    brand: 'Samsung',
    price: 599,
    processor: 'Exynos 2200',
    cameraScore: 82,
    batteryScore: 82,
    performanceScore: 78,
    heatingIssue: true,
    longTermScore: 82,
    pros: ['Flagship features at lower price', 'Good display', 'Decent cameras'],
    cons: ['Exynos can heat up', 'Battery could be better', 'Performance inconsistent'],
    imageUrl: '/phones/samsung-s23-fe.jpg',
    releaseYear: 2023,
    updateYears: 4
  },
  {
    id: '11',
    name: 'Motorola Edge 40 Pro',
    brand: 'Motorola',
    price: 699,
    processor: 'Snapdragon 8 Gen 2',
    cameraScore: 84,
    batteryScore: 88,
    performanceScore: 88,
    heatingIssue: false,
    longTermScore: 72,
    pros: ['125W charging', 'Clean Android', 'Curved display'],
    cons: ['Limited updates', 'Camera not flagship-level', 'Software support uncertain'],
    imageUrl: '/phones/motorola-edge-40-pro.jpg',
    releaseYear: 2023,
    updateYears: 3
  },
  {
    id: '12',
    name: 'ASUS ROG Phone 8',
    brand: 'ASUS',
    price: 999,
    processor: 'Snapdragon 8 Gen 3',
    cameraScore: 78,
    batteryScore: 92,
    performanceScore: 99,
    heatingIssue: false,
    longTermScore: 75,
    pros: ['Best gaming performance', 'Great cooling system', 'Gaming features'],
    cons: ['Thick and heavy', 'Camera not great', 'Expensive for niche use'],
    imageUrl: '/phones/asus-rog-8.jpg',
    releaseYear: 2024,
    updateYears: 3
  },
  {
    id: '13',
    name: 'Realme GT 5 Pro',
    brand: 'Realme',
    price: 549,
    processor: 'Snapdragon 8 Gen 3',
    cameraScore: 82,
    batteryScore: 90,
    performanceScore: 92,
    heatingIssue: false,
    longTermScore: 70,
    pros: ['Flagship chipset at mid-range price', '100W charging', 'Good performance'],
    cons: ['Bloatware', 'Limited updates', 'Plastic frame'],
    imageUrl: '/phones/realme-gt5-pro.jpg',
    releaseYear: 2024,
    updateYears: 2
  },
  {
    id: '14',
    name: 'iPhone SE (2024)',
    brand: 'Apple',
    price: 429,
    processor: 'A15 Bionic',
    cameraScore: 75,
    batteryScore: 70,
    performanceScore: 85,
    heatingIssue: false,
    longTermScore: 88,
    pros: ['Affordable iPhone', 'Great performance', 'Long software support'],
    cons: ['Old design', 'Small battery', 'Single camera'],
    imageUrl: '/phones/iphone-se-2024.jpg',
    releaseYear: 2024,
    updateYears: 5
  },
  {
    id: '15',
    name: 'Samsung Galaxy Z Flip 5',
    brand: 'Samsung',
    price: 999,
    processor: 'Snapdragon 8 Gen 2',
    cameraScore: 85,
    batteryScore: 75,
    performanceScore: 88,
    heatingIssue: false,
    longTermScore: 78,
    pros: ['Compact foldable', 'Fun form factor', 'Good cameras'],
    cons: ['Battery life', 'Crease visible', 'Durability concerns'],
    imageUrl: '/phones/samsung-z-flip-5.jpg',
    releaseYear: 2023,
    updateYears: 5
  },
  {
    id: '16',
    name: 'Poco F6 Pro',
    brand: 'Poco',
    price: 399,
    processor: 'Snapdragon 8 Gen 2',
    cameraScore: 75,
    batteryScore: 88,
    performanceScore: 88,
    heatingIssue: true,
    longTermScore: 65,
    pros: ['Incredible value', 'Flagship performance', 'Fast charging'],
    cons: ['Heavy MIUI skin', 'Can overheat', 'Camera average'],
    imageUrl: '/phones/poco-f6-pro.jpg',
    releaseYear: 2024,
    updateYears: 2
  },
  {
    id: '17',
    name: 'Sony Xperia 1 V',
    brand: 'Sony',
    price: 1399,
    processor: 'Snapdragon 8 Gen 2',
    cameraScore: 93,
    batteryScore: 80,
    performanceScore: 90,
    heatingIssue: true,
    longTermScore: 80,
    pros: ['Pro camera features', '4K display', 'Headphone jack'],
    cons: ['Very expensive', 'Overheating issues', 'Niche audience'],
    imageUrl: '/phones/sony-xperia-1v.jpg',
    releaseYear: 2023,
    updateYears: 3
  },
  {
    id: '18',
    name: 'Oppo Find X7 Ultra',
    brand: 'Oppo',
    price: 949,
    processor: 'Snapdragon 8 Gen 3',
    cameraScore: 95,
    batteryScore: 90,
    performanceScore: 92,
    heatingIssue: false,
    longTermScore: 72,
    pros: ['Hasselblad cameras', 'Great battery', 'Premium build'],
    cons: ['ColorOS bloat', 'Limited updates', 'Regional availability'],
    imageUrl: '/phones/oppo-find-x7-ultra.jpg',
    releaseYear: 2024,
    updateYears: 3
  }
]
