import type { Phone } from './types'

export const phones: Phone[] = [
  {
    id: 'iphone-15-pro-max',
    name: 'iPhone 15 Pro Max',
    brand: 'Apple',
    price: 159900,
    processor: 'A17 Pro',
    cameraScore: 95,
    batteryScore: 88,
    performanceScore: 98,
    heatingIssue: false,
    longTermScore: 95,
    releaseYear: 2023,
    updateYears: 6,
    pros: [
      'Best-in-class video recording',
      'Excellent gaming performance',
      'Titanium design, lightweight',
      '6+ years of software updates'
    ],
    cons: [
      'Premium price point',
      'No expandable storage',
      'Slower charging than competitors'
    ],
    imageUrl: '/phones/iphone-15-pro-max.jpg',
    backImageUrl: '/phones/iphone-15-pro-max-back.jpg'
  },
  {
    id: 'samsung-s24-ultra',
    name: 'Galaxy S24 Ultra',
    brand: 'Samsung',
    price: 134999,
    processor: 'Snapdragon 8 Gen 3',
    cameraScore: 94,
    batteryScore: 90,
    performanceScore: 96,
    heatingIssue: false,
    longTermScore: 90,
    releaseYear: 2024,
    updateYears: 7,
    pros: [
      '200MP camera sensor',
      'Built-in S Pen',
      '7 years of updates promised',
      'Brilliant display'
    ],
    cons: [
      'Heavy at 232g',
      'Expensive',
      'S Pen less useful without Note features'
    ],
    imageUrl: '/phones/samsung-s24-ultra.jpg',
    backImageUrl: '/phones/samsung-s24-ultra-back.jpg'
  },
  {
    id: 'pixel-8-pro',
    name: 'Pixel 8 Pro',
    brand: 'Google',
    price: 106999,
    processor: 'Tensor G3',
    cameraScore: 96,
    batteryScore: 85,
    performanceScore: 88,
    heatingIssue: true,
    longTermScore: 92,
    releaseYear: 2023,
    updateYears: 7,
    pros: [
      'Best photo processing with AI',
      'Pure Android experience',
      '7 years of updates',
      'Magic Eraser & AI features'
    ],
    cons: [
      'Can run warm during intensive tasks',
      'Gaming performance lags behind',
      'Tensor chip less powerful raw'
    ],
    imageUrl: '/phones/pixel-8-pro.jpg',
    backImageUrl: '/phones/pixel-8-pro-back.jpg'
  },
  {
    id: 'oneplus-12',
    name: 'OnePlus 12',
    brand: 'OnePlus',
    price: 64999,
    processor: 'Snapdragon 8 Gen 3',
    cameraScore: 88,
    batteryScore: 92,
    performanceScore: 95,
    heatingIssue: false,
    longTermScore: 82,
    releaseYear: 2024,
    updateYears: 4,
    pros: [
      'Incredible 100W fast charging',
      'Flagship performance at lower price',
      'Great gaming experience',
      'Large 5400mAh battery'
    ],
    cons: [
      'Shorter update commitment',
      'Camera not quite flagship level',
      'OxygenOS has ads'
    ],
    imageUrl: '/phones/oneplus-12.jpg',
    backImageUrl: '/phones/oneplus-12-back.jpg'
  },
  {
    id: 'iphone-15',
    name: 'iPhone 15',
    brand: 'Apple',
    price: 79900,
    processor: 'A16 Bionic',
    cameraScore: 88,
    batteryScore: 82,
    performanceScore: 90,
    heatingIssue: false,
    longTermScore: 92,
    releaseYear: 2023,
    updateYears: 6,
    pros: [
      'Dynamic Island feature',
      'USB-C finally',
      'Great everyday camera',
      'Long software support'
    ],
    cons: [
      '60Hz display still',
      'No telephoto lens',
      'Slower charging'
    ],
    imageUrl: '/phones/iphone-15.jpg',
    backImageUrl: '/phones/iphone-15-back.jpg'
  },
  {
    id: 'samsung-s24',
    name: 'Galaxy S24',
    brand: 'Samsung',
    price: 74999,
    processor: 'Exynos 2400',
    cameraScore: 86,
    batteryScore: 80,
    performanceScore: 88,
    heatingIssue: true,
    longTermScore: 85,
    releaseYear: 2024,
    updateYears: 7,
    pros: [
      'Compact flagship',
      'Galaxy AI features',
      '7 years of updates',
      'Bright display'
    ],
    cons: [
      'Exynos chip runs warmer',
      'Smaller battery',
      'Similar to S23'
    ],
    imageUrl: '/phones/samsung-s24.jpg',
    backImageUrl: '/phones/samsung-s24-back.jpg'
  },
  {
    id: 'pixel-8',
    name: 'Pixel 8',
    brand: 'Google',
    price: 75999,
    processor: 'Tensor G3',
    cameraScore: 92,
    batteryScore: 82,
    performanceScore: 85,
    heatingIssue: true,
    longTermScore: 90,
    releaseYear: 2023,
    updateYears: 7,
    pros: [
      'Excellent camera for price',
      'Clean Android experience',
      'AI photo features',
      'Compact size'
    ],
    cons: [
      'Tensor chip gets warm',
      'Not for heavy gaming',
      'No telephoto lens'
    ],
    imageUrl: '/phones/pixel-8.jpg',
    backImageUrl: '/phones/pixel-8-back.jpg'
  },
  {
    id: 'samsung-a54',
    name: 'Galaxy A54 5G',
    brand: 'Samsung',
    price: 38999,
    processor: 'Exynos 1380',
    cameraScore: 78,
    batteryScore: 88,
    performanceScore: 72,
    heatingIssue: false,
    longTermScore: 80,
    releaseYear: 2023,
    updateYears: 4,
    pros: [
      'Great value for money',
      'Water resistant',
      'Good battery life',
      '4 years of updates'
    ],
    cons: [
      'Slower processor',
      'Plastic build',
      'Camera struggles in low light'
    ],
    imageUrl: '/phones/samsung-a54.jpg',
    backImageUrl: '/phones/samsung-a54-back.jpg'
  },
  {
    id: 'pixel-7a',
    name: 'Pixel 7a',
    brand: 'Google',
    price: 43999,
    processor: 'Tensor G2',
    cameraScore: 88,
    batteryScore: 78,
    performanceScore: 80,
    heatingIssue: true,
    longTermScore: 85,
    releaseYear: 2023,
    updateYears: 5,
    pros: [
      'Flagship camera experience',
      'Clean Android',
      'Wireless charging',
      '90Hz display'
    ],
    cons: [
      'Can overheat',
      'Average battery',
      'Plastic back'
    ],
    imageUrl: '/phones/pixel-7a.jpg',
    backImageUrl: '/phones/pixel-7a-back.jpg'
  },
  {
    id: 'nothing-phone-2',
    name: 'Phone (2)',
    brand: 'Nothing',
    price: 44999,
    processor: 'Snapdragon 8+ Gen 1',
    cameraScore: 80,
    batteryScore: 85,
    performanceScore: 88,
    heatingIssue: false,
    longTermScore: 75,
    releaseYear: 2023,
    updateYears: 3,
    pros: [
      'Unique Glyph interface',
      'Clean software',
      'Flagship chip at mid-range price',
      'Distinctive design'
    ],
    cons: [
      'Short update promise',
      'Camera not flagship level',
      'Newer brand, less proven'
    ],
    imageUrl: '/phones/nothing-phone-2.jpg',
    backImageUrl: '/phones/nothing-phone-2-back.jpg'
  },
  {
    id: 'motorola-edge-40-pro',
    name: 'Edge 40 Pro',
    brand: 'Motorola',
    price: 54999,
    processor: 'Snapdragon 8 Gen 2',
    cameraScore: 82,
    batteryScore: 88,
    performanceScore: 90,
    heatingIssue: false,
    longTermScore: 70,
    releaseYear: 2023,
    updateYears: 3,
    pros: [
      '125W fast charging',
      'Curved display',
      'Stock-like Android',
      'IP68 water resistance'
    ],
    cons: [
      'Only 3 years updates',
      'Camera inconsistent',
      'Motorola support lacking'
    ],
    imageUrl: '/phones/motorola-edge-40-pro.jpg',
    backImageUrl: '/phones/motorola-edge-40-pro-back.jpg'
  },
  {
    id: 'xiaomi-14',
    name: 'Xiaomi 14',
    brand: 'Xiaomi',
    price: 69999,
    processor: 'Snapdragon 8 Gen 3',
    cameraScore: 90,
    batteryScore: 85,
    performanceScore: 94,
    heatingIssue: false,
    longTermScore: 78,
    releaseYear: 2024,
    updateYears: 4,
    pros: [
      'Leica camera partnership',
      'Compact flagship',
      'Fast charging',
      'Great performance'
    ],
    cons: [
      'MIUI has bloatware',
      'Shorter updates than rivals',
      'Limited global availability'
    ],
    imageUrl: '/phones/xiaomi-14.jpg',
    backImageUrl: '/phones/xiaomi-14-back.jpg'
  },
  {
    id: 'realme-gt-5-pro',
    name: 'GT 5 Pro',
    brand: 'Realme',
    price: 44999,
    processor: 'Snapdragon 8 Gen 3',
    cameraScore: 82,
    batteryScore: 90,
    performanceScore: 94,
    heatingIssue: false,
    longTermScore: 72,
    releaseYear: 2024,
    updateYears: 3,
    pros: [
      'Flagship chip at mid-range price',
      '100W fast charging',
      'Great gaming performance',
      '5400mAh battery'
    ],
    cons: [
      'Short update commitment',
      'Realme UI has ads',
      'Camera not consistent'
    ],
    imageUrl: '/phones/realme-gt-5-pro.jpg',
    backImageUrl: '/phones/realme-gt-5-pro-back.jpg'
  },
  {
    id: 'poco-f5-pro',
    name: 'POCO F5 Pro',
    brand: 'POCO',
    price: 29999,
    processor: 'Snapdragon 8+ Gen 1',
    cameraScore: 75,
    batteryScore: 88,
    performanceScore: 88,
    heatingIssue: true,
    longTermScore: 70,
    releaseYear: 2023,
    updateYears: 3,
    pros: [
      'Incredible value',
      'Flagship performance',
      'AMOLED 120Hz display',
      'Good battery life'
    ],
    cons: [
      'Can run hot gaming',
      'Camera average',
      'MIUI bloatware'
    ],
    imageUrl: '/phones/poco-f5-pro.jpg',
    backImageUrl: '/phones/poco-f5-pro-back.jpg'
  },
  {
    id: 'iphone-se-3',
    name: 'iPhone SE (2022)',
    brand: 'Apple',
    price: 49900,
    processor: 'A15 Bionic',
    cameraScore: 72,
    batteryScore: 65,
    performanceScore: 88,
    heatingIssue: false,
    longTermScore: 88,
    releaseYear: 2022,
    updateYears: 5,
    pros: [
      'Powerful A15 chip',
      'Compact design',
      'iOS ecosystem',
      'Long updates'
    ],
    cons: [
      'Small battery',
      'Outdated design',
      'Single rear camera'
    ],
    imageUrl: '/phones/iphone-se-3.jpg',
    backImageUrl: '/phones/iphone-se-3-back.jpg'
  },
  {
    id: 'samsung-a34',
    name: 'Galaxy A34 5G',
    brand: 'Samsung',
    price: 27999,
    processor: 'Dimensity 1080',
    cameraScore: 74,
    batteryScore: 90,
    performanceScore: 68,
    heatingIssue: false,
    longTermScore: 78,
    releaseYear: 2023,
    updateYears: 4,
    pros: [
      'Excellent battery life',
      'AMOLED display',
      'Water resistant',
      'Good for daily use'
    ],
    cons: [
      'Slower processor',
      'Plastic build',
      'No wireless charging'
    ],
    imageUrl: '/phones/samsung-a34.jpg',
    backImageUrl: '/phones/samsung-a34-back.jpg'
  },
  {
    id: 'redmi-note-13-pro',
    name: 'Redmi Note 13 Pro+',
    brand: 'Xiaomi',
    price: 31999,
    processor: 'Dimensity 7200 Ultra',
    cameraScore: 80,
    batteryScore: 92,
    performanceScore: 75,
    heatingIssue: false,
    longTermScore: 72,
    releaseYear: 2024,
    updateYears: 3,
    pros: [
      '200MP camera',
      '120W fast charging',
      'Great display',
      'Good value'
    ],
    cons: [
      'MIUI bloatware',
      'Short updates',
      'Mid-range processor'
    ],
    imageUrl: '/phones/redmi-note-13-pro.jpg',
    backImageUrl: '/phones/redmi-note-13-pro-back.jpg'
  },
  {
    id: 'asus-rog-phone-8',
    name: 'ROG Phone 8 Pro',
    brand: 'ASUS',
    price: 104999,
    processor: 'Snapdragon 8 Gen 3',
    cameraScore: 82,
    batteryScore: 85,
    performanceScore: 99,
    heatingIssue: false,
    longTermScore: 75,
    releaseYear: 2024,
    updateYears: 3,
    pros: [
      'Best gaming performance',
      'Active cooling system',
      '165Hz display',
      'Gaming accessories'
    ],
    cons: [
      'Bulky design',
      'Short update promise',
      'Camera not flagship'
    ],
    imageUrl: '/phones/asus-rog-phone-8.jpg',
    backImageUrl: '/phones/asus-rog-phone-8-back.jpg'
  },
  {
    id: 'sony-xperia-1-v',
    name: 'Xperia 1 V',
    brand: 'Sony',
    price: 109990,
    processor: 'Snapdragon 8 Gen 2',
    cameraScore: 92,
    batteryScore: 82,
    performanceScore: 90,
    heatingIssue: true,
    longTermScore: 80,
    releaseYear: 2023,
    updateYears: 3,
    pros: [
      'Pro-level camera controls',
      '4K OLED display',
      'Headphone jack',
      'Great for content creators'
    ],
    cons: [
      'Very expensive',
      'Can overheat recording 4K',
      'Short update period'
    ],
    imageUrl: '/phones/sony-xperia-1-v.jpg',
    backImageUrl: '/phones/sony-xperia-1-v-back.jpg'
  },
  {
    id: 'oppo-find-x7-ultra',
    name: 'Find X7 Ultra',
    brand: 'OPPO',
    price: 89999,
    processor: 'Snapdragon 8 Gen 3',
    cameraScore: 94,
    batteryScore: 88,
    performanceScore: 94,
    heatingIssue: false,
    longTermScore: 78,
    releaseYear: 2024,
    updateYears: 4,
    pros: [
      'Hasselblad cameras',
      'Dual periscope lenses',
      'Fast charging',
      'Great display'
    ],
    cons: [
      'ColorOS learning curve',
      'Limited global availability',
      'Large and heavy'
    ],
    imageUrl: '/phones/oppo-find-x7-ultra.jpg',
    backImageUrl: '/phones/oppo-find-x7-ultra-back.jpg'
  },

  // ── 50 NEW PREMIUM PHONES ──────────────────────────────────────────────────

  {
    id: 'iphone-16-pro-max',
    name: 'iPhone 16 Pro Max',
    brand: 'Apple',
    price: 189900,
    processor: 'A18 Pro',
    cameraScore: 97,
    batteryScore: 92,
    performanceScore: 99,
    heatingIssue: false,
    longTermScore: 97,
    releaseYear: 2024,
    updateYears: 7,
    pros: ['A18 Pro chip, fastest ever', 'Camera Control button', '5x periscope zoom', '7 years of updates'],
    cons: ['Very expensive', 'Large and heavy', 'No charger in box'],
    imageUrl: '/phones/iphone-16-pro-max.jpg',
    backImageUrl: '/phones/iphone-16-pro-max-back.jpg'
  },
  {
    id: 'iphone-16-pro',
    name: 'iPhone 16 Pro',
    brand: 'Apple',
    price: 134900,
    processor: 'A18 Pro',
    cameraScore: 96,
    batteryScore: 89,
    performanceScore: 99,
    heatingIssue: false,
    longTermScore: 97,
    releaseYear: 2024,
    updateYears: 7,
    pros: ['A18 Pro powerhouse', 'Compact Pro design', 'Camera Control', 'Titanium build'],
    cons: ['Pricey', 'No charger', 'Smaller battery than Pro Max'],
    imageUrl: '/phones/iphone-16-pro.jpg',
    backImageUrl: '/phones/iphone-16-pro-back.jpg'
  },
  {
    id: 'iphone-16',
    name: 'iPhone 16',
    brand: 'Apple',
    price: 79900,
    processor: 'A18',
    cameraScore: 90,
    batteryScore: 88,
    performanceScore: 94,
    heatingIssue: false,
    longTermScore: 95,
    releaseYear: 2024,
    updateYears: 7,
    pros: ['A18 chip with Apple Intelligence', 'Camera Control', 'USB-C fast charge', 'Great value iPhone'],
    cons: ['No ProMotion display', 'No telephoto', 'Average zoom'],
    imageUrl: '/phones/iphone-16.jpg',
    backImageUrl: '/phones/iphone-16-back.jpg'
  },
  {
    id: 'samsung-s25-ultra',
    name: 'Galaxy S25 Ultra',
    brand: 'Samsung',
    price: 139999,
    processor: 'Snapdragon 8 Elite',
    cameraScore: 96,
    batteryScore: 89,
    performanceScore: 99,
    heatingIssue: false,
    longTermScore: 92,
    releaseYear: 2025,
    updateYears: 7,
    pros: ['Snapdragon 8 Elite fastest Android chip', 'S Pen included', '200MP camera', '7 years of updates'],
    cons: ['Extremely expensive', 'Very large device', 'S Pen storage awkward'],
    imageUrl: '/phones/samsung-s25-ultra.jpg',
    backImageUrl: '/phones/samsung-s25-ultra-back.jpg'
  },
  {
    id: 'samsung-s25-plus',
    name: 'Galaxy S25+',
    brand: 'Samsung',
    price: 99999,
    processor: 'Snapdragon 8 Elite',
    cameraScore: 89,
    batteryScore: 92,
    performanceScore: 97,
    heatingIssue: false,
    longTermScore: 90,
    releaseYear: 2025,
    updateYears: 7,
    pros: ['Large battery', 'Bright QHD display', 'Excellent AI features', 'Fast charging'],
    cons: ['No S Pen', 'Expensive for Plus tier', 'Heavy'],
    imageUrl: '/phones/samsung-s25-plus.jpg',
    backImageUrl: '/phones/samsung-s25-plus-back.jpg'
  },
  {
    id: 'samsung-s25',
    name: 'Galaxy S25',
    brand: 'Samsung',
    price: 79999,
    processor: 'Snapdragon 8 Elite',
    cameraScore: 87,
    batteryScore: 84,
    performanceScore: 96,
    heatingIssue: false,
    longTermScore: 90,
    releaseYear: 2025,
    updateYears: 7,
    pros: ['Flagship chip at reasonable price', 'Compact Galaxy AI phone', 'Bright display', '7 years updates'],
    cons: ['Small battery', 'No zoom lens', 'Smaller than Plus/Ultra'],
    imageUrl: '/phones/samsung-s25.jpg',
    backImageUrl: '/phones/samsung-s25-back.jpg'
  },
  {
    id: 'pixel-9-pro-xl',
    name: 'Pixel 9 Pro XL',
    brand: 'Google',
    price: 119999,
    processor: 'Tensor G4',
    cameraScore: 97,
    batteryScore: 90,
    performanceScore: 87,
    heatingIssue: false,
    longTermScore: 95,
    releaseYear: 2024,
    updateYears: 7,
    pros: ['Best AI camera on Android', 'Google AI features first', '7 years updates', 'Large display'],
    cons: ['Tensor G4 not fastest chip', 'Expensive for a Pixel', 'Average gaming performance'],
    imageUrl: '/phones/pixel-9-pro-xl.jpg',
    backImageUrl: '/phones/pixel-9-pro-xl-back.jpg'
  },
  {
    id: 'pixel-9-pro',
    name: 'Pixel 9 Pro',
    brand: 'Google',
    price: 109999,
    processor: 'Tensor G4',
    cameraScore: 96,
    batteryScore: 87,
    performanceScore: 86,
    heatingIssue: false,
    longTermScore: 95,
    releaseYear: 2024,
    updateYears: 7,
    pros: ['Exceptional AI camera', 'Compact Pro design', 'Clean Pixel AI features', '7 years support'],
    cons: ['No periscope zoom', 'Tensor chip behind Snapdragon', 'Premium price'],
    imageUrl: '/phones/pixel-9-pro.jpg',
    backImageUrl: '/phones/pixel-9-pro-back.jpg'
  },
  {
    id: 'pixel-9',
    name: 'Pixel 9',
    brand: 'Google',
    price: 79999,
    processor: 'Tensor G4',
    cameraScore: 92,
    batteryScore: 84,
    performanceScore: 84,
    heatingIssue: false,
    longTermScore: 93,
    releaseYear: 2024,
    updateYears: 7,
    pros: ['Best camera AI under 80K', 'Google Gemini built-in', '7 years updates', 'Clean software'],
    cons: ['No telephoto', 'Average gaming chip', 'No zoom camera'],
    imageUrl: '/phones/pixel-9.jpg',
    backImageUrl: '/phones/pixel-9-back.jpg'
  },
  {
    id: 'oneplus-13',
    name: 'OnePlus 13',
    brand: 'OnePlus',
    price: 69999,
    processor: 'Snapdragon 8 Elite',
    cameraScore: 88,
    batteryScore: 96,
    performanceScore: 97,
    heatingIssue: false,
    longTermScore: 82,
    releaseYear: 2025,
    updateYears: 4,
    pros: ['100W SuperVOOC fast charging', 'Massive 6000mAh battery', 'Flagship chip', 'Excellent value'],
    cons: ['Limited updates vs Samsung/Google', 'Camera behind flagships', 'OxygenOS has minor bloat'],
    imageUrl: '/phones/oneplus-13.jpg',
    backImageUrl: '/phones/oneplus-13-back.jpg'
  },
  {
    id: 'xiaomi-15-ultra',
    name: 'Xiaomi 15 Ultra',
    brand: 'Xiaomi',
    price: 109999,
    processor: 'Snapdragon 8 Elite',
    cameraScore: 98,
    batteryScore: 90,
    performanceScore: 97,
    heatingIssue: false,
    longTermScore: 76,
    releaseYear: 2025,
    updateYears: 4,
    pros: ['Camera beast with Leica', 'Snapdragon 8 Elite', 'Great charging speed', 'Stunning build'],
    cons: ['Short software support', 'MIUI bloat', 'Limited global availability'],
    imageUrl: '/phones/xiaomi-15-ultra.jpg',
    backImageUrl: '/phones/xiaomi-15-ultra-back.jpg'
  },
  {
    id: 'xiaomi-15',
    name: 'Xiaomi 15',
    brand: 'Xiaomi',
    price: 74999,
    processor: 'Snapdragon 8 Elite',
    cameraScore: 90,
    batteryScore: 88,
    performanceScore: 96,
    heatingIssue: false,
    longTermScore: 75,
    releaseYear: 2025,
    updateYears: 4,
    pros: ['Snapdragon 8 Elite at mid-flagship price', 'Leica cameras', 'Compact form factor', 'Fast charging'],
    cons: ['MIUI bloatware', 'Only 4 years updates', 'Limited India stock'],
    imageUrl: '/phones/xiaomi-15.jpg',
    backImageUrl: '/phones/xiaomi-15-back.jpg'
  },
  {
    id: 'samsung-z-fold-6',
    name: 'Galaxy Z Fold 6',
    brand: 'Samsung',
    price: 164999,
    processor: 'Snapdragon 8 Gen 3',
    cameraScore: 86,
    batteryScore: 78,
    performanceScore: 93,
    heatingIssue: false,
    longTermScore: 85,
    releaseYear: 2024,
    updateYears: 7,
    pros: ['Large foldable display', 'S Pen support', 'Galaxy AI features', 'Premium build'],
    cons: ['Very expensive', 'Heavy', 'Battery life could be better'],
    imageUrl: '/phones/samsung-z-fold-6.jpg',
    backImageUrl: '/phones/samsung-z-fold-6-back.jpg'
  },
  {
    id: 'samsung-z-flip-6',
    name: 'Galaxy Z Flip 6',
    brand: 'Samsung',
    price: 109999,
    processor: 'Snapdragon 8 Gen 3',
    cameraScore: 83,
    batteryScore: 76,
    performanceScore: 90,
    heatingIssue: false,
    longTermScore: 80,
    releaseYear: 2024,
    updateYears: 7,
    pros: ['Compact clamshell foldable', 'Improved hinge', 'Galaxy AI', 'Great camera for the form factor'],
    cons: ['Battery life is weak', 'Expensive for features', 'Crease still visible'],
    imageUrl: '/phones/samsung-z-flip-6.jpg',
    backImageUrl: '/phones/samsung-z-flip-6-back.jpg'
  },
  {
    id: 'vivo-x200-pro',
    name: 'vivo X200 Pro',
    brand: 'vivo',
    price: 94999,
    processor: 'Dimensity 9400',
    cameraScore: 97,
    batteryScore: 92,
    performanceScore: 95,
    heatingIssue: false,
    longTermScore: 76,
    releaseYear: 2024,
    updateYears: 3,
    pros: ['Zeiss camera co-engineered', 'Periscope zoom excellence', '90W fast charge', 'AMOLED display'],
    cons: ['Short update commitment', 'Limited availability', 'OriginOS learning curve'],
    imageUrl: '/phones/vivo-x200-pro.jpg',
    backImageUrl: '/phones/vivo-x200-pro-back.jpg'
  },
  {
    id: 'oppo-find-x8-pro',
    name: 'OPPO Find X8 Pro',
    brand: 'OPPO',
    price: 99999,
    processor: 'Dimensity 9400',
    cameraScore: 95,
    batteryScore: 91,
    performanceScore: 95,
    heatingIssue: false,
    longTermScore: 77,
    releaseYear: 2024,
    updateYears: 4,
    pros: ['Hasselblad camera system', 'Dual periscope lenses', 'Dimensity 9400 leading chip', 'Fast charging'],
    cons: ['ColorOS has bloat', 'Limited India support', 'Expensive'],
    imageUrl: '/phones/oppo-find-x8-pro.jpg',
    backImageUrl: '/phones/oppo-find-x8-pro-back.jpg'
  },
  {
    id: 'nothing-phone-3a-pro',
    name: 'Nothing Phone 3a Pro',
    brand: 'Nothing',
    price: 39999,
    processor: 'Snapdragon 7s Gen 3',
    cameraScore: 80,
    batteryScore: 88,
    performanceScore: 82,
    heatingIssue: false,
    longTermScore: 78,
    releaseYear: 2025,
    updateYears: 3,
    pros: ['Unique Glyph interface upgraded', 'Clean Android-like software', 'Affordable', 'Good build quality'],
    cons: ['Mid-range chip', 'Short update period', 'Camera not flagship level'],
    imageUrl: '/phones/nothing-phone-3a-pro.jpg',
    backImageUrl: '/phones/nothing-phone-3a-pro-back.jpg'
  },
  {
    id: 'nothing-phone-3a',
    name: 'Nothing Phone 3a',
    brand: 'Nothing',
    price: 29999,
    processor: 'Snapdragon 7s Gen 3',
    cameraScore: 78,
    batteryScore: 86,
    performanceScore: 80,
    heatingIssue: false,
    longTermScore: 76,
    releaseYear: 2025,
    updateYears: 3,
    pros: ['Excellent value', 'Distinctive design with Glyph', 'Clean software', 'Good battery'],
    cons: ['Mid-range chip', 'Average camera', 'Only 3 years updates'],
    imageUrl: '/phones/nothing-phone-3a.jpg',
    backImageUrl: '/phones/nothing-phone-3a-back.jpg'
  },
  {
    id: 'motorola-edge-50-ultra',
    name: 'Edge 50 Ultra',
    brand: 'Motorola',
    price: 59999,
    processor: 'Snapdragon 8s Gen 3',
    cameraScore: 85,
    batteryScore: 89,
    performanceScore: 88,
    heatingIssue: false,
    longTermScore: 72,
    releaseYear: 2024,
    updateYears: 3,
    pros: ['125W TurboPower charging', 'Curved OLED display', 'pOS clean software', 'Good cameras'],
    cons: ['Short software support', 'Brand less premium', 'Camera inconsistent vs flagships'],
    imageUrl: '/phones/motorola-edge-50-ultra.jpg',
    backImageUrl: '/phones/motorola-edge-50-ultra-back.jpg'
  },
  {
    id: 'motorola-edge-50-pro',
    name: 'Edge 50 Pro',
    brand: 'Motorola',
    price: 31999,
    processor: 'Snapdragon 7 Gen 3',
    cameraScore: 81,
    batteryScore: 87,
    performanceScore: 84,
    heatingIssue: false,
    longTermScore: 70,
    releaseYear: 2024,
    updateYears: 3,
    pros: ['68W fast charging', 'Great display quality', 'Clean software', 'Good value'],
    cons: ['Only 3 years updates', 'Mid-range chip', 'Performance limited vs flagships'],
    imageUrl: '/phones/motorola-edge-50-pro.jpg',
    backImageUrl: '/phones/motorola-edge-50-pro-back.jpg'
  },
  {
    id: 'realme-gt-7-pro',
    name: 'Realme GT 7 Pro',
    brand: 'Realme',
    price: 59999,
    processor: 'Snapdragon 8 Elite',
    cameraScore: 83,
    batteryScore: 92,
    performanceScore: 96,
    heatingIssue: false,
    longTermScore: 70,
    releaseYear: 2024,
    updateYears: 3,
    pros: ['Snapdragon 8 Elite at budget-flagship price', '120W fast charging', 'Strong performance', 'Good display'],
    cons: ['Realme UI bloatware', 'Short update commitment', 'Camera behind class leaders'],
    imageUrl: '/phones/realme-gt-7-pro.jpg',
    backImageUrl: '/phones/realme-gt-7-pro-back.jpg'
  },
  {
    id: 'redmi-note-14-pro-plus',
    name: 'Redmi Note 14 Pro+',
    brand: 'Xiaomi',
    price: 34999,
    processor: 'Dimensity 9300+',
    cameraScore: 82,
    batteryScore: 90,
    performanceScore: 86,
    heatingIssue: false,
    longTermScore: 72,
    releaseYear: 2024,
    updateYears: 3,
    pros: ['200MP camera on a budget', '90W HyperCharge', 'Flagship chip', 'AMOLED 120Hz display'],
    cons: ['MIUI bloatware', 'Limited updates', 'Heavy at 220g'],
    imageUrl: '/phones/redmi-note-14-pro-plus.jpg',
    backImageUrl: '/phones/redmi-note-14-pro-plus-back.jpg'
  },
  {
    id: 'samsung-a55',
    name: 'Galaxy A55 5G',
    brand: 'Samsung',
    price: 39999,
    processor: 'Exynos 1480',
    cameraScore: 82,
    batteryScore: 88,
    performanceScore: 75,
    heatingIssue: false,
    longTermScore: 85,
    releaseYear: 2024,
    updateYears: 4,
    pros: ['Sleek metal design', 'Bright AMOLED display', '4 years updates', 'Good cameras'],
    cons: ['No wireless charging', 'Slow charging speed', 'Mid-range performance'],
    imageUrl: '/phones/samsung-a55.jpg',
    backImageUrl: '/phones/samsung-a55-back.jpg'
  },
  {
    id: 'samsung-a35',
    name: 'Galaxy A35 5G',
    brand: 'Samsung',
    price: 26999,
    processor: 'Exynos 1380',
    cameraScore: 76,
    batteryScore: 89,
    performanceScore: 70,
    heatingIssue: false,
    longTermScore: 82,
    releaseYear: 2024,
    updateYears: 4,
    pros: ['Excellent battery life', 'AMOLED display', 'IP67 dust & water resistant', '4 years updates'],
    cons: ['Slow charging', 'Plastic back', 'Camera lags behind A55'],
    imageUrl: '/phones/samsung-a35.jpg',
    backImageUrl: '/phones/samsung-a35-back.jpg'
  },
  {
    id: 'asus-rog-phone-9-pro',
    name: 'ROG Phone 9 Pro',
    brand: 'ASUS',
    price: 119999,
    processor: 'Snapdragon 8 Elite',
    cameraScore: 82,
    batteryScore: 88,
    performanceScore: 99,
    heatingIssue: false,
    longTermScore: 76,
    releaseYear: 2024,
    updateYears: 3,
    pros: ['Best gaming smartphone ever', 'AeroActive Cooler', '185Hz display', 'Massive 5800mAh battery'],
    cons: ['Large and bulky', 'Camera not flagship level', 'Niche gaming audience'],
    imageUrl: '/phones/asus-rog-phone-9-pro.jpg',
    backImageUrl: '/phones/asus-rog-phone-9-pro-back.jpg'
  },
  {
    id: 'poco-x7-pro',
    name: 'POCO X7 Pro',
    brand: 'POCO',
    price: 26999,
    processor: 'Dimensity 8400',
    cameraScore: 78,
    batteryScore: 90,
    performanceScore: 88,
    heatingIssue: false,
    longTermScore: 70,
    releaseYear: 2025,
    updateYears: 3,
    pros: ['Incredible price-to-performance', '90W fast charging', 'AMOLED 120Hz display', 'Good battery capacity'],
    cons: ['MIUI bloatware', 'Only 3 years updates', 'Camera average for price'],
    imageUrl: '/phones/poco-x7-pro.jpg',
    backImageUrl: '/phones/poco-x7-pro-back.jpg'
  },
  {
    id: 'poco-f7-pro',
    name: 'POCO F7 Pro',
    brand: 'POCO',
    price: 34999,
    processor: 'Snapdragon 8 Gen 3',
    cameraScore: 80,
    batteryScore: 88,
    performanceScore: 95,
    heatingIssue: true,
    longTermScore: 68,
    releaseYear: 2025,
    updateYears: 3,
    pros: ['Flagship chip at mid-range price', 'Blazing performance', '120W charging', 'AMOLED display'],
    cons: ['Can run hot under load', 'MIUI bloatware', 'Short software support'],
    imageUrl: '/phones/poco-f7-pro.jpg',
    backImageUrl: '/phones/poco-f7-pro-back.jpg'
  },
  {
    id: 'oneplus-nord-4',
    name: 'Nord 4',
    brand: 'OnePlus',
    price: 29999,
    processor: 'Snapdragon 7+ Gen 3',
    cameraScore: 79,
    batteryScore: 89,
    performanceScore: 86,
    heatingIssue: false,
    longTermScore: 76,
    releaseYear: 2024,
    updateYears: 4,
    pros: ['100W fast charging', 'All-metal design', 'Smooth 120Hz AMOLED', 'Clean OxygenOS'],
    cons: ['No wireless charging', 'No telephoto', 'Limited camera versatility'],
    imageUrl: '/phones/oneplus-nord-4.jpg',
    backImageUrl: '/phones/oneplus-nord-4-back.jpg'
  },
  {
    id: 'oneplus-nord-ce4',
    name: 'Nord CE 4',
    brand: 'OnePlus',
    price: 24999,
    processor: 'Snapdragon 7 Gen 3',
    cameraScore: 76,
    batteryScore: 86,
    performanceScore: 82,
    heatingIssue: false,
    longTermScore: 74,
    releaseYear: 2024,
    updateYears: 3,
    pros: ['100W fast charging', 'Slim design', 'Clean software', 'Good value'],
    cons: ['No wireless charging', 'Only 3 years updates', 'Average camera'],
    imageUrl: '/phones/oneplus-nord-ce4.jpg',
    backImageUrl: '/phones/oneplus-nord-ce4-back.jpg'
  },
  {
    id: 'vivo-v40-pro',
    name: 'vivo V40 Pro',
    brand: 'vivo',
    price: 49999,
    processor: 'Snapdragon 7 Gen 3',
    cameraScore: 88,
    batteryScore: 84,
    performanceScore: 84,
    heatingIssue: false,
    longTermScore: 74,
    releaseYear: 2024,
    updateYears: 3,
    pros: ['Zeiss portrait cameras', 'Slim & premium design', 'Good AMOLED 120Hz', 'Nice photography features'],
    cons: ['Limited updates', 'OriginOS learning curve', 'Mid-range chip only'],
    imageUrl: '/phones/vivo-v40-pro.jpg',
    backImageUrl: '/phones/vivo-v40-pro-back.jpg'
  },
  {
    id: 'vivo-v40',
    name: 'vivo V40',
    brand: 'vivo',
    price: 39999,
    processor: 'Snapdragon 7 Gen 3',
    cameraScore: 85,
    batteryScore: 83,
    performanceScore: 82,
    heatingIssue: false,
    longTermScore: 73,
    releaseYear: 2024,
    updateYears: 3,
    pros: ['Zeiss optics', 'Slim design', 'AMOLED display', 'Stylish build'],
    cons: ['Short update period', 'Average battery capacity', 'Bloatware present'],
    imageUrl: '/phones/vivo-v40.jpg',
    backImageUrl: '/phones/vivo-v40-back.jpg'
  },
  {
    id: 'infinix-zero-40',
    name: 'Infinix Zero 40 5G',
    brand: 'Infinix',
    price: 24999,
    processor: 'Dimensity 8200 Ultimate',
    cameraScore: 78,
    batteryScore: 88,
    performanceScore: 82,
    heatingIssue: false,
    longTermScore: 68,
    releaseYear: 2024,
    updateYears: 2,
    pros: ['Budget 5G flagship performance', '70W charging', 'Good display', 'Impressive build for price'],
    cons: ['Very short software support', 'Bloatware', 'Limited camera performance'],
    imageUrl: '/phones/infinix-zero-40.jpg',
    backImageUrl: '/phones/infinix-zero-40-back.jpg'
  },
  {
    id: 'tecno-phantom-x2-pro',
    name: 'Phantom X2 Pro',
    brand: 'TECNO',
    price: 34999,
    processor: 'Dimensity 9000',
    cameraScore: 82,
    batteryScore: 85,
    performanceScore: 88,
    heatingIssue: false,
    longTermScore: 66,
    releaseYear: 2023,
    updateYears: 2,
    pros: ['Retractable portrait lens unique', 'Flagship chip', 'Good cameras', 'Premium design'],
    cons: ['Short update cycle', 'Niche brand', 'Low resale value'],
    imageUrl: '/phones/tecno-phantom-x2-pro.jpg',
    backImageUrl: '/phones/tecno-phantom-x2-pro-back.jpg'
  },
  {
    id: 'huawei-pura-70-ultra',
    name: 'Pura 70 Ultra',
    brand: 'Huawei',
    price: 149999,
    processor: 'Kirin 9010',
    cameraScore: 96,
    batteryScore: 86,
    performanceScore: 82,
    heatingIssue: false,
    longTermScore: 62,
    releaseYear: 2024,
    updateYears: 3,
    pros: ['Exceptional camera with variable aperture', 'Satellite connectivity', 'Premium titanium build', 'Unique design'],
    cons: ['No Google services', 'Kirin chip behind Snapdragon in raw performance', 'Very expensive', 'Limited apps'],
    imageUrl: '/phones/huawei-pura-70-ultra.jpg',
    backImageUrl: '/phones/huawei-pura-70-ultra-back.jpg'
  },
  {
    id: 'oppo-reno-13-pro',
    name: 'Reno 13 Pro',
    brand: 'OPPO',
    price: 49999,
    processor: 'Dimensity 8350',
    cameraScore: 83,
    batteryScore: 87,
    performanceScore: 83,
    heatingIssue: false,
    longTermScore: 74,
    releaseYear: 2025,
    updateYears: 3,
    pros: ['Premium portrait photography', 'Slim design', 'Fast charging', 'Good display'],
    cons: ['ColorOS bloat', 'Limited updates', 'Camera behind flagships'],
    imageUrl: '/phones/oppo-reno-13-pro.jpg',
    backImageUrl: '/phones/oppo-reno-13-pro-back.jpg'
  },
  {
    id: 'honor-magic-7-pro',
    name: 'Magic 7 Pro',
    brand: 'HONOR',
    price: 89999,
    processor: 'Snapdragon 8 Elite',
    cameraScore: 92,
    batteryScore: 88,
    performanceScore: 96,
    heatingIssue: false,
    longTermScore: 74,
    releaseYear: 2024,
    updateYears: 3,
    pros: ['Snapdragon 8 Elite with flagship spec', 'AI Silhouette camera tech', 'Fast charging', 'Good display'],
    cons: ['Short update promise', 'Limited brand recognition globally', 'No Google on some variants'],
    imageUrl: '/phones/honor-magic-7-pro.jpg',
    backImageUrl: '/phones/honor-magic-7-pro-back.jpg'
  },
  {
    id: 'sony-xperia-5-vi',
    name: 'Xperia 5 VI',
    brand: 'Sony',
    price: 89999,
    processor: 'Snapdragon 8 Gen 3',
    cameraScore: 90,
    batteryScore: 85,
    performanceScore: 92,
    heatingIssue: false,
    longTermScore: 82,
    releaseYear: 2024,
    updateYears: 4,
    pros: ['Compact flagship', 'Pro camera controls', 'Headphone jack', 'Great for creators'],
    cons: ['Very niche phone', 'Expensive', 'Average battery'],
    imageUrl: '/phones/sony-xperia-5-vi.jpg',
    backImageUrl: '/phones/sony-xperia-5-vi-back.jpg'
  },
  {
    id: 'lg-wing-foldable',
    name: 'Galaxy Z Fold Special Edition',
    brand: 'Samsung',
    price: 199999,
    processor: 'Snapdragon 8 Gen 3',
    cameraScore: 88,
    batteryScore: 79,
    performanceScore: 95,
    heatingIssue: false,
    longTermScore: 84,
    releaseYear: 2024,
    updateYears: 7,
    pros: ['Exclusive special edition design', '7 years updates', 'Galaxy AI', 'Collector item'],
    cons: ['Extremely expensive', 'Limited availability', 'Same hardware as Z Fold 6'],
    imageUrl: '/phones/samsung-z-fold-special.jpg',
    backImageUrl: '/phones/samsung-z-fold-special-back.jpg'
  },
  {
    id: 'iphone-15-plus',
    name: 'iPhone 15 Plus',
    brand: 'Apple',
    price: 89900,
    processor: 'A16 Bionic',
    cameraScore: 87,
    batteryScore: 92,
    performanceScore: 90,
    heatingIssue: false,
    longTermScore: 93,
    releaseYear: 2023,
    updateYears: 6,
    pros: ['Largest iPhone battery life', 'Big 6.7 display', 'USB-C', 'Clean iOS'],
    cons: ['60Hz display', 'No telephoto', 'A16 not latest chip'],
    imageUrl: '/phones/iphone-15-plus.jpg',
    backImageUrl: '/phones/iphone-15-plus-back.jpg'
  },
  {
    id: 'pixel-8a',
    name: 'Pixel 8a',
    brand: 'Google',
    price: 52999,
    processor: 'Tensor G3',
    cameraScore: 87,
    batteryScore: 82,
    performanceScore: 83,
    heatingIssue: true,
    longTermScore: 90,
    releaseYear: 2024,
    updateYears: 7,
    pros: ['Flagship camera AI on a budget', '7 years updates', '120Hz display', 'Good value'],
    cons: ['Tensor can run warm', 'Average gaming chip', 'Slow charging'],
    imageUrl: '/phones/pixel-8a.jpg',
    backImageUrl: '/phones/pixel-8a-back.jpg'
  },
  {
    id: 'samsung-a16-5g',
    name: 'Galaxy A16 5G',
    brand: 'Samsung',
    price: 17999,
    processor: 'Dimensity 6300',
    cameraScore: 68,
    batteryScore: 88,
    performanceScore: 62,
    heatingIssue: false,
    longTermScore: 76,
    releaseYear: 2024,
    updateYears: 6,
    pros: ['6 years software updates', 'Large battery', 'Affordable 5G', 'Decent display'],
    cons: ['Entry-level performance', 'Slow charging', 'Basic camera'],
    imageUrl: '/phones/samsung-a16-5g.jpg',
    backImageUrl: '/phones/samsung-a16-5g-back.jpg'
  },
  {
    id: 'motorola-razr-50-ultra',
    name: 'Razr 50 Ultra',
    brand: 'Motorola',
    price: 99999,
    processor: 'Snapdragon 8s Gen 3',
    cameraScore: 84,
    batteryScore: 78,
    performanceScore: 87,
    heatingIssue: false,
    longTermScore: 72,
    releaseYear: 2024,
    updateYears: 3,
    pros: ['Largest flip-phone cover display', 'Premium look & feel', 'Decent cameras', 'Fun form factor'],
    cons: ['Short battery life', 'Expensive for specs', 'Limited updates vs Samsung flip'],
    imageUrl: '/phones/motorola-razr-50-ultra.jpg',
    backImageUrl: '/phones/motorola-razr-50-ultra-back.jpg'
  },
  {
    id: 'realme-13-pro-plus',
    name: 'Realme 13 Pro+',
    brand: 'Realme',
    price: 29999,
    processor: 'Snapdragon 7s Gen 3',
    cameraScore: 82,
    batteryScore: 86,
    performanceScore: 83,
    heatingIssue: false,
    longTermScore: 70,
    releaseYear: 2024,
    updateYears: 3,
    pros: ['Sony LYT-700C sensor', '80W charging', 'OLED 120Hz display', 'Good value'],
    cons: ['Realme UI bloat', 'Not flagship chip', 'Short updates'],
    imageUrl: '/phones/realme-13-pro-plus.jpg',
    backImageUrl: '/phones/realme-13-pro-plus-back.jpg'
  },
  {
    id: 'poco-m7-pro',
    name: 'POCO M7 Pro 5G',
    brand: 'POCO',
    price: 17999,
    processor: 'Dimensity 7300',
    cameraScore: 72,
    batteryScore: 87,
    performanceScore: 76,
    heatingIssue: false,
    longTermScore: 68,
    releaseYear: 2024,
    updateYears: 2,
    pros: ['Budget 5G', 'Good battery life', '33W charging', 'AMOLED 120Hz display'],
    cons: ['MIUI ads', 'Only 2 years updates', 'Average camera'],
    imageUrl: '/phones/poco-m7-pro.jpg',
    backImageUrl: '/phones/poco-m7-pro-back.jpg'
  },
  {
    id: 'iphone-16-plus',
    name: 'iPhone 16 Plus',
    brand: 'Apple',
    price: 89900,
    processor: 'A18',
    cameraScore: 89,
    batteryScore: 94,
    performanceScore: 93,
    heatingIssue: false,
    longTermScore: 95,
    releaseYear: 2024,
    updateYears: 7,
    pros: ['Best battery life on any iPhone', 'Apple Intelligence AI', 'Large 6.7" display', 'Camera Control button'],
    cons: ['No ProMotion 120Hz', 'No telephoto camera', 'Less popular than Pro'],
    imageUrl: '/phones/iphone-16-plus.jpg',
    backImageUrl: '/phones/iphone-16-plus-back.jpg'
  },
  {
    id: 'samsung-s24-fe',
    name: 'Galaxy S24 FE',
    brand: 'Samsung',
    price: 54999,
    processor: 'Exynos 2500',
    cameraScore: 84,
    batteryScore: 87,
    performanceScore: 82,
    heatingIssue: false,
    longTermScore: 85,
    releaseYear: 2024,
    updateYears: 7,
    pros: ['7 years updates for an FE phone', 'Galaxy AI features', 'Bright 120Hz display', 'Good cameras'],
    cons: ['Exynos chip not fastest', 'Expensive for Fan Edition', 'Slightly behind S24 in performance'],
    imageUrl: '/phones/samsung-s24-fe.jpg',
    backImageUrl: '/phones/samsung-s24-fe-back.jpg'
  },
  {
    id: 'oneplus-open',
    name: 'OnePlus Open',
    brand: 'OnePlus',
    price: 139999,
    processor: 'Snapdragon 8 Gen 2',
    cameraScore: 88,
    batteryScore: 82,
    performanceScore: 93,
    heatingIssue: false,
    longTermScore: 80,
    releaseYear: 2023,
    updateYears: 4,
    pros: ['Best large foldable display quality', 'Optics by Hasselblad', 'Great hinge mechanism', 'Less heavy than Fold'],
    cons: ['Older chip', 'Short update promise for a premium phone', 'Expensive'],
    imageUrl: '/phones/oneplus-open.jpg',
    backImageUrl: '/phones/oneplus-open-back.jpg'
  },
  {
    id: 'nokia-xl21',
    name: 'Nokia XR21',
    brand: 'Nokia',
    price: 54999,
    processor: 'Snapdragon 695',
    cameraScore: 74,
    batteryScore: 84,
    performanceScore: 70,
    heatingIssue: false,
    longTermScore: 88,
    releaseYear: 2023,
    updateYears: 5,
    pros: ['Extremely durable & ruggedized', 'MIL-SPEC toughness', 'Clean Android', 'Long update support'],
    cons: ['Mid-range chipset', 'Slow charging', 'Expensive for specs'],
    imageUrl: '/phones/nokia-xr21.jpg',
    backImageUrl: '/phones/nokia-xr21-back.jpg'
  },
  {
    id: 'fairphone-5',
    name: 'Fairphone 5',
    brand: 'Fairphone',
    price: 69999,
    processor: 'QCM6490',
    cameraScore: 76,
    batteryScore: 88,
    performanceScore: 72,
    heatingIssue: false,
    longTermScore: 98,
    releaseYear: 2023,
    updateYears: 10,
    pros: ['10 years software support', 'Fully repairable & modular', 'Ethical sourcing', 'Replaceable battery'],
    cons: ['Niche audience', 'Mid-range performance', 'High price for specs'],
    imageUrl: '/phones/fairphone-5.jpg',
    backImageUrl: '/phones/fairphone-5-back.jpg'
  },
  {
    id: 'oneplus-12r',
    name: 'OnePlus 12R',
    brand: 'OnePlus',
    price: 39999,
    processor: 'Snapdragon 8 Gen 1',
    cameraScore: 80,
    batteryScore: 90,
    performanceScore: 87,
    heatingIssue: false,
    longTermScore: 76,
    releaseYear: 2024,
    updateYears: 4,
    pros: ['100W fast charging', 'Large 5000mAh battery', 'Smooth 120Hz display', 'Clean OxygenOS'],
    cons: ['Older Snapdragon 8 Gen 1 chip', 'Camera not on par with flagships', 'No wireless charging'],
    imageUrl: '/phones/oneplus-12r.jpg',
    backImageUrl: '/phones/oneplus-12r-back.jpg'
  },

  // ── BATCH 2: OnePlus ──────────────────────────────────────────────────────
  { id: 'oneplus-15', name: 'OnePlus 15', brand: 'OnePlus', price: 74999, processor: 'Snapdragon 8 Elite', cameraScore: 90, batteryScore: 96, performanceScore: 97, heatingIssue: false, longTermScore: 82, releaseYear: 2025, updateYears: 4, pros: ['Hasselblad cameras', '100W SuperVOOC', 'Snapdragon 8 Elite', 'Large 6000mAh battery'], cons: ['Short update period', 'OxygenOS bloat', 'Camera slightly behind Xiaomi/Samsung'], imageUrl: '/phones/oneplus-15.jpg', backImageUrl: '/phones/oneplus-15-back.jpg' },
  { id: 'oneplus-13s', name: 'OnePlus 13s', brand: 'OnePlus', price: 64999, processor: 'Snapdragon 8 Gen 3', cameraScore: 88, batteryScore: 94, performanceScore: 95, heatingIssue: false, longTermScore: 80, releaseYear: 2025, updateYears: 4, pros: ['Refined design over 13', 'Fast charging', 'Good software', 'Great value'], cons: ['Same chip as before', 'No periscope zoom', 'Short updates'], imageUrl: '/phones/oneplus-13s.jpg', backImageUrl: '/phones/oneplus-13s-back.jpg' },
  { id: 'oneplus-15r', name: 'OnePlus 15R', brand: 'OnePlus', price: 42999, processor: 'Dimensity 9300+', cameraScore: 82, batteryScore: 92, performanceScore: 88, heatingIssue: false, longTermScore: 78, releaseYear: 2025, updateYears: 4, pros: ['80W fast charging', 'Great performance for price', 'Smooth 120Hz display', 'Clean software'], cons: ['Camera not flagship level', 'Limited updates', 'No wireless charging'], imageUrl: '/phones/oneplus-15r.jpg', backImageUrl: '/phones/oneplus-15r-back.jpg' },
  { id: 'oneplus-nord-5', name: 'OnePlus Nord 5', brand: 'OnePlus', price: 34999, processor: 'Snapdragon 7+ Gen 3', cameraScore: 80, batteryScore: 88, performanceScore: 85, heatingIssue: false, longTermScore: 76, releaseYear: 2025, updateYears: 3, pros: ['100W fast charging', 'Smooth display', 'Metal build', 'Clean OS'], cons: ['No periscope zoom', 'Mid-range chip', 'Only 3 years updates'], imageUrl: '/phones/oneplus-nord-5.jpg', backImageUrl: '/phones/oneplus-nord-5-back.jpg' },
  { id: 'oneplus-nord-6', name: 'OnePlus Nord 6', brand: 'OnePlus', price: 39999, processor: 'Snapdragon 8s Gen 3', cameraScore: 82, batteryScore: 90, performanceScore: 87, heatingIssue: false, longTermScore: 76, releaseYear: 2025, updateYears: 3, pros: ['Near-flagship chip', '80W charging', 'Premium build', 'Good cameras'], cons: ['Short update promise', 'No wireless charging', 'Camera behind flagships'], imageUrl: '/phones/oneplus-nord-6.jpg', backImageUrl: '/phones/oneplus-nord-6-back.jpg' },
  { id: 'oneplus-nord-ce5', name: 'OnePlus Nord CE 5 5G', brand: 'OnePlus', price: 24999, processor: 'Snapdragon 7 Gen 3', cameraScore: 76, batteryScore: 86, performanceScore: 82, heatingIssue: false, longTermScore: 72, releaseYear: 2025, updateYears: 3, pros: ['80W fast charging', 'Slim design', 'Good display', 'Affordable'], cons: ['Mid-range only', 'Camera average', 'Basic spec overall'], imageUrl: '/phones/oneplus-nord-ce5.jpg', backImageUrl: '/phones/oneplus-nord-ce5-back.jpg' },
  { id: 'oneplus-nord-ce3-lite', name: 'OnePlus Nord CE 3 Lite 5G', brand: 'OnePlus', price: 19999, processor: 'Snapdragon 695', cameraScore: 70, batteryScore: 84, performanceScore: 70, heatingIssue: false, longTermScore: 68, releaseYear: 2023, updateYears: 3, pros: ['Affordable 5G', 'Large 5000mAh battery', 'Good display', 'Clean OS'], cons: ['Entry-level chip', 'Plastic body', 'Camera heavily limited'], imageUrl: '/phones/oneplus-nord-ce3-lite.jpg', backImageUrl: '/phones/oneplus-nord-ce3-lite-back.jpg' },

  // ── BATCH 2: Apple iPhones ────────────────────────────────────────────────
  { id: 'iphone-17-pro-max', name: 'iPhone 17 Pro Max', brand: 'Apple', price: 199900, processor: 'A19 Pro', cameraScore: 99, batteryScore: 94, performanceScore: 99, heatingIssue: false, longTermScore: 98, releaseYear: 2025, updateYears: 7, pros: ['A19 Pro fastest chip ever', 'Foldable display rumoured', 'AI-enhanced camera', '7 years updates'], cons: ['Extremely expensive', 'Very heavy', 'No charger included'], imageUrl: '/phones/iphone-17-pro-max.jpg', backImageUrl: '/phones/iphone-17-pro-max-back.jpg' },
  { id: 'iphone-17-pro', name: 'iPhone 17 Pro', brand: 'Apple', price: 144900, processor: 'A19 Pro', cameraScore: 98, batteryScore: 91, performanceScore: 99, heatingIssue: false, longTermScore: 98, releaseYear: 2025, updateYears: 7, pros: ['Titanium design', 'A19 Pro', 'Camera Control', 'ProRes video'], cons: ['Expensive', 'No charger', 'Heavy titanium body'], imageUrl: '/phones/iphone-17-pro.jpg', backImageUrl: '/phones/iphone-17-pro-back.jpg' },
  { id: 'iphone-17', name: 'iPhone 17', brand: 'Apple', price: 89900, processor: 'A19', cameraScore: 92, batteryScore: 89, performanceScore: 95, heatingIssue: false, longTermScore: 96, releaseYear: 2025, updateYears: 7, pros: ['A19 Apple Intelligence', 'Camera Control', 'ProMotion 120Hz expected', '7 years updates'], cons: ['No telephoto', 'No charger', 'Less powerful than Pro'], imageUrl: '/phones/iphone-17.jpg', backImageUrl: '/phones/iphone-17-back.jpg' },
  { id: 'iphone-17-plus', name: 'iPhone 17 Plus', brand: 'Apple', price: 99900, processor: 'A19', cameraScore: 91, batteryScore: 96, performanceScore: 94, heatingIssue: false, longTermScore: 96, releaseYear: 2025, updateYears: 7, pros: ['Largest iPhone battery ever', 'Apple Intelligence AI', 'Large display', '7 years updates'], cons: ['No Pro camera', 'No telephoto', 'Very large form factor'], imageUrl: '/phones/iphone-17-plus.jpg', backImageUrl: '/phones/iphone-17-plus-back.jpg' },
  { id: 'iphone-15-pro-max-v2', name: 'iPhone 15 Pro Max', brand: 'Apple', price: 149900, processor: 'A17 Pro', cameraScore: 95, batteryScore: 88, performanceScore: 97, heatingIssue: false, longTermScore: 96, releaseYear: 2023, updateYears: 7, pros: ['Titanium design', '5x periscope zoom', 'USB-C 3.2', 'A17 Pro'], cons: ['Expensive', 'Heavy', 'Gets warm gaming'], imageUrl: '/phones/iphone-15-pro-max-v2.jpg', backImageUrl: '/phones/iphone-15-pro-max-v2-back.jpg' },
  // ── BATCH 3: Samsung ─────────────────────────────────────────────────────
  { id: 'samsung-s26-ultra', name: 'Galaxy S26 Ultra', brand: 'Samsung', price: 149999, processor: 'Snapdragon 8 Elite 2', cameraScore: 97, batteryScore: 90, performanceScore: 99, heatingIssue: false, longTermScore: 93, releaseYear: 2026, updateYears: 7, pros: ['Next-gen Elite chip', 'S Pen included', '200MP camera', '7 years updates'], cons: ['Premium price', 'Very large', 'Incremental over S25 Ultra'], imageUrl: '/phones/samsung-s26-ultra.jpg', backImageUrl: '/phones/samsung-s26-ultra-back.jpg' },
  { id: 'samsung-s26-plus', name: 'Galaxy S26+', brand: 'Samsung', price: 104999, processor: 'Snapdragon 8 Elite 2', cameraScore: 90, batteryScore: 92, performanceScore: 98, heatingIssue: false, longTermScore: 91, releaseYear: 2026, updateYears: 7, pros: ['Latest Elite chip', 'Large bright display', 'Galaxy AI', '7 years updates'], cons: ['No S Pen', 'Expensive', 'A bit heavy'], imageUrl: '/phones/samsung-s26-plus.jpg', backImageUrl: '/phones/samsung-s26-plus-back.jpg' },
  { id: 'samsung-s26', name: 'Galaxy S26', brand: 'Samsung', price: 84999, processor: 'Snapdragon 8 Elite 2', cameraScore: 88, batteryScore: 85, performanceScore: 97, heatingIssue: false, longTermScore: 91, releaseYear: 2026, updateYears: 7, pros: ['Flagship chip', 'Compact', 'Galaxy AI', '7 years updates'], cons: ['Small battery', 'No zoom', 'Expensive for size'], imageUrl: '/phones/samsung-s26.jpg', backImageUrl: '/phones/samsung-s26-back.jpg' },
  { id: 'samsung-z-fold-7', name: 'Galaxy Z Fold 7', brand: 'Samsung', price: 179999, processor: 'Snapdragon 8 Elite 2', cameraScore: 88, batteryScore: 80, performanceScore: 97, heatingIssue: false, longTermScore: 86, releaseYear: 2026, updateYears: 7, pros: ['Slimmer foldable design', 'Galaxy AI', 'S Pen', '7 years updates'], cons: ['Very expensive', 'Heavy', 'Battery under 5000mAh'], imageUrl: '/phones/samsung-z-fold-7.jpg', backImageUrl: '/phones/samsung-z-fold-7-back.jpg' },
  { id: 'samsung-z-flip-7', name: 'Galaxy Z Flip 7', brand: 'Samsung', price: 114999, processor: 'Snapdragon 8 Elite 2', cameraScore: 85, batteryScore: 78, performanceScore: 96, heatingIssue: false, longTermScore: 82, releaseYear: 2026, updateYears: 7, pros: ['Latest chip in a flip', 'Large cover screen', 'Galaxy AI', '7 years updates'], cons: ['Small battery', 'Crease visible', 'Expensive'], imageUrl: '/phones/samsung-z-flip-7.jpg', backImageUrl: '/phones/samsung-z-flip-7-back.jpg' },
  { id: 'samsung-a36-5g', name: 'Galaxy A36 5G', brand: 'Samsung', price: 29999, processor: 'Exynos 1580', cameraScore: 78, batteryScore: 88, performanceScore: 74, heatingIssue: false, longTermScore: 83, releaseYear: 2025, updateYears: 4, pros: ['4 years updates', 'AMOLED display', 'Good battery', 'IP67'], cons: ['Mid-range chip', 'Slow charging', 'No flagship features'], imageUrl: '/phones/samsung-a36-5g.jpg', backImageUrl: '/phones/samsung-a36-5g-back.jpg' },
  { id: 'samsung-m17-5g', name: 'Galaxy M17 5G', brand: 'Samsung', price: 15999, processor: 'Dimensity 6100+', cameraScore: 66, batteryScore: 90, performanceScore: 62, heatingIssue: false, longTermScore: 70, releaseYear: 2025, updateYears: 3, pros: ['Long battery life', 'Budget 5G', 'Big display', 'Decent value'], cons: ['Entry-level processor', 'Basic camera', 'Plastic build'], imageUrl: '/phones/samsung-m17-5g.jpg', backImageUrl: '/phones/samsung-m17-5g-back.jpg' },

  // ── BATCH 3: Motorola ─────────────────────────────────────────────────────
  { id: 'motorola-edge-70-ultra', name: 'Motorola Edge 70 Ultra', brand: 'Motorola', price: 64999, processor: 'Snapdragon 8 Elite', cameraScore: 88, batteryScore: 88, performanceScore: 96, heatingIssue: false, longTermScore: 72, releaseYear: 2025, updateYears: 3, pros: ['Flagship chip', '125W charging', 'Clean Android', 'Premium curved design'], cons: ['Only 3 years updates', 'Camera behind Samsung/Google', 'Limited Motorola support'], imageUrl: '/phones/motorola-edge-70-ultra.jpg', backImageUrl: '/phones/motorola-edge-70-ultra-back.jpg' },
  { id: 'motorola-edge-70-pro', name: 'Motorola Edge 70 Pro', brand: 'Motorola', price: 44999, processor: 'Snapdragon 8s Gen 3', cameraScore: 84, batteryScore: 87, performanceScore: 88, heatingIssue: false, longTermScore: 70, releaseYear: 2025, updateYears: 3, pros: ['Near-flagship chip', '100W charging', 'Stock-like Android', 'Good display'], cons: ['Short updates', 'Camera inconsistent', 'Motorola brand less prestigious'], imageUrl: '/phones/motorola-edge-70-pro.jpg', backImageUrl: '/phones/motorola-edge-70-pro-back.jpg' },
  { id: 'motorola-edge-70-fusion', name: 'Motorola Edge 70 Fusion', brand: 'Motorola', price: 29999, processor: 'Dimensity 7300', cameraScore: 78, batteryScore: 85, performanceScore: 80, heatingIssue: false, longTermScore: 68, releaseYear: 2025, updateYears: 3, pros: ['68W charging', 'Clean software', 'Good mid-range display', 'Reliable battery'], cons: ['Mid-range chip', 'Only 3 years updates', 'Camera average'], imageUrl: '/phones/motorola-edge-70-fusion.jpg', backImageUrl: '/phones/motorola-edge-70-fusion-back.jpg' },
  { id: 'motorola-edge-60-ultra', name: 'Motorola Edge 60 Ultra', brand: 'Motorola', price: 54999, processor: 'Snapdragon 8 Gen 3', cameraScore: 86, batteryScore: 88, performanceScore: 93, heatingIssue: false, longTermScore: 71, releaseYear: 2024, updateYears: 3, pros: ['125W fast charging', 'Curved OLED', 'Clean software', 'Flagship chip'], cons: ['Short software support', 'Camera not class-leading', 'Limited Motorola updates'], imageUrl: '/phones/motorola-edge-60-ultra.jpg', backImageUrl: '/phones/motorola-edge-60-ultra-back.jpg' },
  { id: 'motorola-edge-60-pro', name: 'Motorola Edge 60 Pro', brand: 'Motorola', price: 37999, processor: 'Snapdragon 7 Gen 3', cameraScore: 82, batteryScore: 86, performanceScore: 84, heatingIssue: false, longTermScore: 69, releaseYear: 2024, updateYears: 3, pros: ['68W charging', 'Good display', 'Clean Android', 'Decent value'], cons: ['Only 3 years updates', 'Camera not flagship', 'Mid-range chip'], imageUrl: '/phones/motorola-edge-60-pro.jpg', backImageUrl: '/phones/motorola-edge-60-pro-back.jpg' },
  { id: 'motorola-edge-60-fusion', name: 'Motorola Edge 60 Fusion', brand: 'Motorola', price: 22999, processor: 'Dimensity 7300', cameraScore: 74, batteryScore: 85, performanceScore: 77, heatingIssue: false, longTermScore: 66, releaseYear: 2024, updateYears: 3, pros: ['Affordable', 'Good battery', 'Clean Android', 'Solid build'], cons: ['Basic camera', 'Average chip', 'Short software support'], imageUrl: '/phones/motorola-edge-60-fusion.jpg', backImageUrl: '/phones/motorola-edge-60-fusion-back.jpg' },
  { id: 'motorola-g96', name: 'Motorola G96', brand: 'Motorola', price: 19999, processor: 'Snapdragon 6s Gen 3', cameraScore: 72, batteryScore: 86, performanceScore: 74, heatingIssue: false, longTermScore: 65, releaseYear: 2025, updateYears: 2, pros: ['Solid mid-range value', 'Good battery', 'Clean software', 'Reliable build'], cons: ['Short updates', 'Basic camera', 'Not for performance users'], imageUrl: '/phones/motorola-g96.jpg', backImageUrl: '/phones/motorola-g96-back.jpg' },
  { id: 'motorola-g86', name: 'Motorola G86', brand: 'Motorola', price: 17999, processor: 'Snapdragon 6 Gen 3', cameraScore: 70, batteryScore: 84, performanceScore: 72, heatingIssue: false, longTermScore: 64, releaseYear: 2024, updateYears: 2, pros: ['Budget friendly', 'Good battery', 'Stock Android', 'Reliable'], cons: ['Basic chip', 'Low camera quality', 'Short updates'], imageUrl: '/phones/motorola-g86.jpg', backImageUrl: '/phones/motorola-g86-back.jpg' },
  { id: 'motorola-g76', name: 'Motorola G76', brand: 'Motorola', price: 14999, processor: 'Snapdragon 6s Gen 3', cameraScore: 66, batteryScore: 85, performanceScore: 68, heatingIssue: false, longTermScore: 62, releaseYear: 2024, updateYears: 2, pros: ['Very affordable', 'Good battery', 'Stock Android', '5G'], cons: ['Very basic chip', 'Entry camera', 'Short support lifecycle'], imageUrl: '/phones/motorola-g76.jpg', backImageUrl: '/phones/motorola-g76-back.jpg' },
  { id: 'motorola-g57-power', name: 'Motorola G57 Power', brand: 'Motorola', price: 11999, processor: 'Dimensity 6100+', cameraScore: 60, batteryScore: 92, performanceScore: 62, heatingIssue: false, longTermScore: 60, releaseYear: 2024, updateYears: 2, pros: ['Massive 5000mAh+ battery', 'Affordable entry 5G', 'Clean software', 'Great backup phone'], cons: ['Very basic specs', 'Plasticky build', 'Poor camera'], imageUrl: '/phones/motorola-g57-power.jpg', backImageUrl: '/phones/motorola-g57-power-back.jpg' },

  // ── BATCH 3: Redmi ───────────────────────────────────────────────────────
  { id: 'redmi-note-15-pro-plus', name: 'Redmi Note 15 Pro+ 5G', brand: 'Xiaomi', price: 29999, processor: 'Dimensity 9300+', cameraScore: 85, batteryScore: 90, performanceScore: 88, heatingIssue: false, longTermScore: 70, releaseYear: 2025, updateYears: 3, pros: ['200MP camera', '90W fast charging', 'Flagship chip in mid-range', 'AMOLED display'], cons: ['MIUI bloatware', 'Short updates', 'Heavy device'], imageUrl: '/phones/redmi-note-15-pro-plus.jpg', backImageUrl: '/phones/redmi-note-15-pro-plus-back.jpg' },
  { id: 'redmi-note-15-pro', name: 'Redmi Note 15 Pro 5G', brand: 'Xiaomi', price: 24999, processor: 'Dimensity 8300 Ultra', cameraScore: 82, batteryScore: 88, performanceScore: 84, heatingIssue: false, longTermScore: 68, releaseYear: 2025, updateYears: 3, pros: ['Good camera for price', '67W charging', 'AMOLED 120Hz', 'Solid build'], cons: ['MIUI ads', 'Short software support', 'Not flagship chip'], imageUrl: '/phones/redmi-note-15-pro.jpg', backImageUrl: '/phones/redmi-note-15-pro-back.jpg' },
  { id: 'redmi-note-15', name: 'Redmi Note 15 5G', brand: 'Xiaomi', price: 18999, processor: 'Snapdragon 7s Gen 2', cameraScore: 74, batteryScore: 87, performanceScore: 76, heatingIssue: false, longTermScore: 65, releaseYear: 2025, updateYears: 2, pros: ['5G at entry price', 'Good battery', '33W charging', 'AMOLED display'], cons: ['Basic chip', 'MIUI bloat', 'Camera disappointing'], imageUrl: '/phones/redmi-note-15.jpg', backImageUrl: '/phones/redmi-note-15-back.jpg' },
  { id: 'redmi-note-14-pro', name: 'Redmi Note 14 Pro 5G', brand: 'Xiaomi', price: 22999, processor: 'Dimensity 7300 Ultra', cameraScore: 80, batteryScore: 87, performanceScore: 80, heatingIssue: false, longTermScore: 67, releaseYear: 2024, updateYears: 3, pros: ['50MP OIS camera', '67W charging', 'AMOLED display', 'Good value'], cons: ['MIUI bloatware', 'Short updates', 'Mid-range chip'], imageUrl: '/phones/redmi-note-14-pro.jpg', backImageUrl: '/phones/redmi-note-14-pro-back.jpg' },
  { id: 'redmi-note-14-se', name: 'Redmi Note 14 SE 5G', brand: 'Xiaomi', price: 17999, processor: 'Snapdragon 4 Gen 2', cameraScore: 70, batteryScore: 86, performanceScore: 70, heatingIssue: false, longTermScore: 63, releaseYear: 2024, updateYears: 2, pros: ['Affordable 5G', 'Big battery', 'Decent display', 'Reliable'], cons: ['Basic chip', 'MIUI ads', 'Camera average'], imageUrl: '/phones/redmi-note-14-se.jpg', backImageUrl: '/phones/redmi-note-14-se-back.jpg' },
  { id: 'redmi-13-5g', name: 'Redmi 13 5G', brand: 'Xiaomi', price: 13999, processor: 'Snapdragon 4 Gen 2', cameraScore: 66, batteryScore: 85, performanceScore: 66, heatingIssue: false, longTermScore: 62, releaseYear: 2024, updateYears: 2, pros: ['Very affordable 5G', 'Decent battery', '33W charging', 'Big display'], cons: ['Basic specs', 'MIUI ads', 'Low camera quality'], imageUrl: '/phones/redmi-13-5g.jpg', backImageUrl: '/phones/redmi-13-5g-back.jpg' },
  { id: 'redmi-12-5g', name: 'Redmi 12 5G', brand: 'Xiaomi', price: 11999, processor: 'Snapdragon 4 Gen 1', cameraScore: 62, batteryScore: 84, performanceScore: 62, heatingIssue: false, longTermScore: 60, releaseYear: 2023, updateYears: 2, pros: ['Budget 5G phone', 'Good battery', 'Clean enough for basic use', 'IP53 splash resistant'], cons: ['Very basic camera', 'MIUI bloat', 'Old chip'], imageUrl: '/phones/redmi-12-5g.jpg', backImageUrl: '/phones/redmi-12-5g-back.jpg' },
  { id: 'redmi-a4-5g', name: 'Redmi A4 5G', brand: 'Xiaomi', price: 9999, processor: 'Snapdragon 4s Gen 2', cameraScore: 55, batteryScore: 83, performanceScore: 58, heatingIssue: false, longTermScore: 58, releaseYear: 2024, updateYears: 2, pros: ['Cheapest 5G', 'Big battery', 'Basic needs covered', 'Good display for price'], cons: ['Very low performance', 'Basic camera', 'MIUI ads'], imageUrl: '/phones/redmi-a4-5g.jpg', backImageUrl: '/phones/redmi-a4-5g-back.jpg' },
  { id: 'redmi-a3', name: 'Redmi A3', brand: 'Xiaomi', price: 8499, processor: 'Helio G36', cameraScore: 50, batteryScore: 82, performanceScore: 52, heatingIssue: false, longTermScore: 55, releaseYear: 2024, updateYears: 2, pros: ['Ultra budget phone', 'Big 5000mAh battery', 'Large display', 'Decent for calls/WhatsApp'], cons: ['Very weak chip', 'Basic 4G only', 'Poor camera', 'MIUI'], imageUrl: '/phones/redmi-a3.jpg', backImageUrl: '/phones/redmi-a3-back.jpg' },
  // ── BATCH 4: POCO ────────────────────────────────────────────────────────
  { id: 'poco-f7-ultra', name: 'POCO F7 Ultra', brand: 'POCO', price: 49999, processor: 'Snapdragon 8 Elite', cameraScore: 86, batteryScore: 88, performanceScore: 98, heatingIssue: true, longTermScore: 68, releaseYear: 2025, updateYears: 3, pros: ['Snapdragon 8 Elite performance beast', '120W charging', 'AMOLED 144Hz display', 'Best value flagship chip'], cons: ['Runs hot under load', 'MIUI bloatware', 'Camera behind Samsung/Google'], imageUrl: '/phones/poco-f7-ultra.jpg', backImageUrl: '/phones/poco-f7-ultra-back.jpg' },
  { id: 'poco-x8-pro', name: 'POCO X8 Pro', brand: 'POCO', price: 34999, processor: 'Snapdragon 8 Gen 2', cameraScore: 82, batteryScore: 88, performanceScore: 92, heatingIssue: false, longTermScore: 66, releaseYear: 2024, updateYears: 3, pros: ['Strong chip for price', '67W fast charging', 'AMOLED 120Hz', 'Gaming performance'], cons: ['MIUI heavy', 'Camera inconsistent', 'No wireless charging'], imageUrl: '/phones/poco-x8-pro.jpg', backImageUrl: '/phones/poco-x8-pro-back.jpg' },
  { id: 'poco-x8', name: 'POCO X8', brand: 'POCO', price: 26999, processor: 'Dimensity 9300+', cameraScore: 78, batteryScore: 86, performanceScore: 88, heatingIssue: false, longTermScore: 64, releaseYear: 2024, updateYears: 3, pros: ['Flagship chip at budget price', '90W charging', 'AMOLED 120Hz', 'Great performance'], cons: ['MIUI bloat', 'Short support', 'Camera left behind'], imageUrl: '/phones/poco-x8.jpg', backImageUrl: '/phones/poco-x8-back.jpg' },
  { id: 'poco-x7', name: 'POCO X7', brand: 'POCO', price: 22999, processor: 'Dimensity 8400', cameraScore: 75, batteryScore: 88, performanceScore: 84, heatingIssue: false, longTermScore: 62, releaseYear: 2025, updateYears: 3, pros: ['Great price performance', '90W charging', 'Solid display', 'Big battery'], cons: ['MIUI heavy', 'Camera underwhelming', 'Short updates'], imageUrl: '/phones/poco-x7.jpg', backImageUrl: '/phones/poco-x7-back.jpg' },
  { id: 'poco-x6-neo', name: 'POCO X6 Neo', brand: 'POCO', price: 17999, processor: 'Dimensity 6080', cameraScore: 68, batteryScore: 86, performanceScore: 70, heatingIssue: false, longTermScore: 60, releaseYear: 2024, updateYears: 2, pros: ['Budget 5G', 'Good battery', 'Decent display', 'Affordable'], cons: ['Basic chip', 'MIUI ads', 'Camera average'], imageUrl: '/phones/poco-x6-neo.jpg', backImageUrl: '/phones/poco-x6-neo-back.jpg' },
  { id: 'poco-m8-5g', name: 'POCO M8 5G', brand: 'POCO', price: 13999, processor: 'MediaTek Dimensity 6300', cameraScore: 62, batteryScore: 84, performanceScore: 66, heatingIssue: false, longTermScore: 58, releaseYear: 2025, updateYears: 2, pros: ['Entry 5G', 'Good battery', 'Big display', 'Affordable'], cons: ['Budget specs', 'MIUI bloat', 'Basic camera'], imageUrl: '/phones/poco-m8-5g.jpg', backImageUrl: '/phones/poco-m8-5g-back.jpg' },
  { id: 'poco-c71', name: 'POCO C71', brand: 'POCO', price: 8999, processor: 'Helio G85', cameraScore: 52, batteryScore: 80, performanceScore: 55, heatingIssue: false, longTermScore: 54, releaseYear: 2025, updateYears: 2, pros: ['Ultra cheap', 'Basic functions work fine', 'Decent display for class', 'Long battery'], cons: ['Very basic chip', 'MIUI ads', 'Poor camera', 'No 5G'], imageUrl: '/phones/poco-c71.jpg', backImageUrl: '/phones/poco-c71-back.jpg' },

  // ── BATCH 4: OPPO ────────────────────────────────────────────────────────
  { id: 'oppo-find-x9-ultra', name: 'Oppo Find X9 Ultra', brand: 'OPPO', price: 114999, processor: 'Snapdragon 8 Elite 2', cameraScore: 98, batteryScore: 90, performanceScore: 97, heatingIssue: false, longTermScore: 76, releaseYear: 2026, updateYears: 4, pros: ['Hasselblad triple periscope cameras', 'Fastest chip', '100W+ charging', 'Premium build'], cons: ['Expensive', 'Limited India support', 'ColorOS bloat'], imageUrl: '/phones/oppo-find-x9-ultra.jpg', backImageUrl: '/phones/oppo-find-x9-ultra-back.jpg' },
  { id: 'oppo-find-x9-pro', name: 'Oppo Find X9 Pro', brand: 'OPPO', price: 89999, processor: 'Snapdragon 8 Elite 2', cameraScore: 94, batteryScore: 89, performanceScore: 96, heatingIssue: false, longTermScore: 74, releaseYear: 2026, updateYears: 4, pros: ['Hasselblad cameras', 'Flagship chip', 'Fast charging', 'Premium design'], cons: ['Limited updates', 'ColorOS bloat', 'Limited India service'], imageUrl: '/phones/oppo-find-x9-pro.jpg', backImageUrl: '/phones/oppo-find-x9-pro-back.jpg' },
  { id: 'oppo-find-x9', name: 'Oppo Find X9', brand: 'OPPO', price: 69999, processor: 'Dimensity 9500', cameraScore: 90, batteryScore: 88, performanceScore: 93, heatingIssue: false, longTermScore: 73, releaseYear: 2026, updateYears: 4, pros: ['Great flagship camera', 'Fast charging', 'OLED display', 'Slim design'], cons: ['Limited India availability', 'ColorOS', 'Short update support'], imageUrl: '/phones/oppo-find-x9.jpg', backImageUrl: '/phones/oppo-find-x9-back.jpg' },
  { id: 'oppo-reno15-pro', name: 'Oppo Reno15 Pro', brand: 'OPPO', price: 54999, processor: 'Snapdragon 8s Gen 4', cameraScore: 86, batteryScore: 87, performanceScore: 88, heatingIssue: false, longTermScore: 72, releaseYear: 2026, updateYears: 3, pros: ['Slim design', 'Good portrait camera', 'Fast charging', 'Premium OLED'], cons: ['ColorOS bloat', 'Short support', 'Camera behind class leaders'], imageUrl: '/phones/oppo-reno15-pro.jpg', backImageUrl: '/phones/oppo-reno15-pro-back.jpg' },
  { id: 'oppo-reno15', name: 'Oppo Reno15', brand: 'OPPO', price: 39999, processor: 'Dimensity 8350', cameraScore: 82, batteryScore: 85, performanceScore: 84, heatingIssue: false, longTermScore: 70, releaseYear: 2026, updateYears: 3, pros: ['Stylish slim design', 'Good camera', 'AMOLED display', 'Fast charging'], cons: ['ColorOS', 'Limited support', 'Average chip'], imageUrl: '/phones/oppo-reno15.jpg', backImageUrl: '/phones/oppo-reno15-back.jpg' },
  { id: 'oppo-reno14-pro', name: 'Oppo Reno14 Pro', brand: 'OPPO', price: 49999, processor: 'Dimensity 9300+', cameraScore: 85, batteryScore: 86, performanceScore: 89, heatingIssue: false, longTermScore: 72, releaseYear: 2025, updateYears: 3, pros: ['Flagship chipset', 'Good camera system', '80W fast charging', 'Slim design'], cons: ['ColorOS bloatware', 'Short update promise', 'Limited service centres'], imageUrl: '/phones/oppo-reno14-pro.jpg', backImageUrl: '/phones/oppo-reno14-pro-back.jpg' },
  { id: 'oppo-reno14', name: 'Oppo Reno14', brand: 'OPPO', price: 34999, processor: 'Dimensity 8350', cameraScore: 80, batteryScore: 84, performanceScore: 82, heatingIssue: false, longTermScore: 69, releaseYear: 2025, updateYears: 3, pros: ['Portrait photography', 'Slim profile', 'AMOLED display', 'Decent value'], cons: ['Short updates', 'ColorOS', 'Mid-range chip'], imageUrl: '/phones/oppo-reno14.jpg', backImageUrl: '/phones/oppo-reno14-back.jpg' },
  { id: 'oppo-k13', name: 'Oppo K13', brand: 'OPPO', price: 24999, processor: 'Snapdragon 7 Gen 3', cameraScore: 76, batteryScore: 88, performanceScore: 82, heatingIssue: false, longTermScore: 66, releaseYear: 2025, updateYears: 3, pros: ['Good mid-range value', '80W charging', 'Decent camera', 'AMOLED display'], cons: ['ColorOS', 'Average camera', 'Limited updates'], imageUrl: '/phones/oppo-k13.jpg', backImageUrl: '/phones/oppo-k13-back.jpg' },
  { id: 'oppo-a5-pro', name: 'Oppo A5 Pro', brand: 'OPPO', price: 17999, processor: 'Snapdragon 6 Gen 1', cameraScore: 70, batteryScore: 87, performanceScore: 72, heatingIssue: false, longTermScore: 62, releaseYear: 2024, updateYears: 2, pros: ['Affordable', 'Big battery', 'Decent display', 'IP68 on a budget'], cons: ['Basic chip', 'ColorOS bloat', 'Camera average'], imageUrl: '/phones/oppo-a5-pro.jpg', backImageUrl: '/phones/oppo-a5-pro-back.jpg' },
  { id: 'oppo-a3', name: 'Oppo A3', brand: 'OPPO', price: 14999, processor: 'Snapdragon 4 Gen 2', cameraScore: 64, batteryScore: 85, performanceScore: 66, heatingIssue: false, longTermScore: 60, releaseYear: 2024, updateYears: 2, pros: ['Budget entry', 'Good battery', 'Decent display', 'IP65'], cons: ['Basic chip', 'ColorOS', 'Camera underwhelming'], imageUrl: '/phones/oppo-a3.jpg', backImageUrl: '/phones/oppo-a3-back.jpg' },

  // ── BATCH 4: vivo ────────────────────────────────────────────────────────
  { id: 'vivo-x300-ultra', name: 'Vivo X300 Ultra', brand: 'vivo', price: 119999, processor: 'Snapdragon 8 Elite 2', cameraScore: 99, batteryScore: 90, performanceScore: 97, heatingIssue: false, longTermScore: 74, releaseYear: 2026, updateYears: 3, pros: ['Best Zeiss camera ever on a phone', 'Periscope + ultrawide excellence', 'Fastest chip', 'Fast wireless charging'], cons: ['Only 3 years updates', 'Limited India availability', 'OriginOS curve'], imageUrl: '/phones/vivo-x300-ultra.jpg', backImageUrl: '/phones/vivo-x300-ultra-back.jpg' },
  { id: 'vivo-x300-pro', name: 'Vivo X300 Pro', brand: 'vivo', price: 89999, processor: 'Snapdragon 8 Elite 2', cameraScore: 96, batteryScore: 88, performanceScore: 96, heatingIssue: false, longTermScore: 72, releaseYear: 2026, updateYears: 3, pros: ['Zeiss optics', 'Periscope zoom', '100W fast charging', 'Flagship chip'], cons: ['Short updates', 'OriginOS', 'Limited availability'], imageUrl: '/phones/vivo-x300-pro.jpg', backImageUrl: '/phones/vivo-x300-pro-back.jpg' },
  { id: 'vivo-x300', name: 'Vivo X300', brand: 'vivo', price: 69999, processor: 'Dimensity 9500', cameraScore: 91, batteryScore: 87, performanceScore: 93, heatingIssue: false, longTermScore: 70, releaseYear: 2026, updateYears: 3, pros: ['Zeiss cameras', 'Solid flagship chip', 'Fast charging', 'Slim design'], cons: ['Short update cycle', 'OriginOS', 'Limited support in India'], imageUrl: '/phones/vivo-x300.jpg', backImageUrl: '/phones/vivo-x300-back.jpg' },
  { id: 'vivo-v70-pro', name: 'Vivo V70 Pro', brand: 'vivo', price: 54999, processor: 'Snapdragon 7+ Gen 3', cameraScore: 88, batteryScore: 86, performanceScore: 85, heatingIssue: false, longTermScore: 72, releaseYear: 2025, updateYears: 3, pros: ['Zeiss portrait cameras', 'Slim premium design', '80W charging', 'Good AI photography'], cons: ['Short updates', 'OriginOS learning curve', 'Not flagship chip'], imageUrl: '/phones/vivo-v70-pro.jpg', backImageUrl: '/phones/vivo-v70-pro-back.jpg' },
  { id: 'vivo-v70', name: 'Vivo V70', brand: 'vivo', price: 39999, processor: 'Dimensity 7300 Ultra', cameraScore: 84, batteryScore: 84, performanceScore: 80, heatingIssue: false, longTermScore: 70, releaseYear: 2025, updateYears: 3, pros: ['Portrait photography', 'Slim body', 'Good display', 'Fast charging'], cons: ['Short updates', 'OriginOS', 'Mid-range chip'], imageUrl: '/phones/vivo-v70.jpg', backImageUrl: '/phones/vivo-v70-back.jpg' },
  { id: 'vivo-v60-pro', name: 'Vivo V60 Pro', brand: 'vivo', price: 49999, processor: 'Snapdragon 7 Gen 3', cameraScore: 86, batteryScore: 85, performanceScore: 83, heatingIssue: false, longTermScore: 71, releaseYear: 2025, updateYears: 3, pros: ['Zeiss cameras', 'Good AMOLED', '80W charging', 'Slim design'], cons: ['Expensive for mid-range chip', 'Short support', 'Camera can be inconsistent'], imageUrl: '/phones/vivo-v60-pro.jpg', backImageUrl: '/phones/vivo-v60-pro-back.jpg' },
  { id: 'vivo-v60', name: 'Vivo V60', brand: 'vivo', price: 34999, processor: 'Snapdragon 7 Gen 3', cameraScore: 82, batteryScore: 83, performanceScore: 80, heatingIssue: false, longTermScore: 68, releaseYear: 2025, updateYears: 3, pros: ['Great portrait phone', 'Zeiss optics', 'Slim design', 'Good display'], cons: ['Short update promise', 'OriginOS bloat', 'Average battery'], imageUrl: '/phones/vivo-v60.jpg', backImageUrl: '/phones/vivo-v60-back.jpg' },
  { id: 'vivo-t5-5g', name: 'Vivo T5 5G', brand: 'vivo', price: 22999, processor: 'Dimensity 8300 Ultra', cameraScore: 76, batteryScore: 88, performanceScore: 84, heatingIssue: false, longTermScore: 65, releaseYear: 2025, updateYears: 2, pros: ['Fast chip for price', '80W charging', 'Decent display', 'Good gaming phone'], cons: ['Short updates', 'OriginOS', 'Camera average'], imageUrl: '/phones/vivo-t5-5g.jpg', backImageUrl: '/phones/vivo-t5-5g-back.jpg' },
  { id: 'vivo-t5x-5g', name: 'Vivo T5x 5G', brand: 'vivo', price: 16999, processor: 'Snapdragon 6 Gen 1', cameraScore: 68, batteryScore: 86, performanceScore: 72, heatingIssue: false, longTermScore: 62, releaseYear: 2025, updateYears: 2, pros: ['Budget 5G', 'Good battery', 'Decent display', 'Solid build for price'], cons: ['Mid-range chip only', 'OriginOS', 'Basic camera'], imageUrl: '/phones/vivo-t5x-5g.jpg', backImageUrl: '/phones/vivo-t5x-5g-back.jpg' },
  { id: 'vivo-y200', name: 'Vivo Y200', brand: 'vivo', price: 19999, processor: 'Snapdragon 4 Gen 2', cameraScore: 70, batteryScore: 88, performanceScore: 68, heatingIssue: false, longTermScore: 60, releaseYear: 2024, updateYears: 2, pros: ['Long battery life', 'Affordable', 'AMOLED display', 'Reliable'], cons: ['Basic chip', 'OriginOS', 'Camera limited'], imageUrl: '/phones/vivo-y200.jpg', backImageUrl: '/phones/vivo-y200-back.jpg' },

  // ── BATCH 4: Nothing ─────────────────────────────────────────────────────
  { id: 'nothing-phone-4', name: 'Nothing Phone 4', brand: 'Nothing', price: 64999, processor: 'Snapdragon 8 Gen 4', cameraScore: 88, batteryScore: 88, performanceScore: 93, heatingIssue: false, longTermScore: 82, releaseYear: 2026, updateYears: 4, pros: ['Flagship chip', 'Unique Glyph 3.0', 'Clean Android', 'Great display'], cons: ['Short updates vs Apple/Samsung', 'Camera behind class leaders', 'Niche brand'], imageUrl: '/phones/nothing-phone-4.jpg', backImageUrl: '/phones/nothing-phone-4-back.jpg' },
  { id: 'nothing-phone-4a-pro', name: 'Nothing Phone 4a Pro', brand: 'Nothing', price: 44999, processor: 'Snapdragon 8s Gen 4', cameraScore: 84, batteryScore: 87, performanceScore: 88, heatingIssue: false, longTermScore: 80, releaseYear: 2026, updateYears: 3, pros: ['Near-flagship chip', 'Glyph interface', 'Clean OS', 'Good display'], cons: ['Only 3 years updates', 'Brand still niche', 'Camera not flagship'], imageUrl: '/phones/nothing-phone-4a-pro.jpg', backImageUrl: '/phones/nothing-phone-4a-pro-back.jpg' },
  { id: 'nothing-phone-4a', name: 'Nothing Phone 4a', brand: 'Nothing', price: 34999, processor: 'Snapdragon 7s Gen 3', cameraScore: 80, batteryScore: 86, performanceScore: 82, heatingIssue: false, longTermScore: 78, releaseYear: 2026, updateYears: 3, pros: ['Affordable Nothing', 'Glyph lights', 'Clean software', 'Good build'], cons: ['Mid-range chip', 'Short support', 'Camera average'], imageUrl: '/phones/nothing-phone-4a.jpg', backImageUrl: '/phones/nothing-phone-4a-back.jpg' },
  { id: 'nothing-phone-3', name: 'Nothing Phone 3', brand: 'Nothing', price: 54999, processor: 'Snapdragon 8 Gen 3', cameraScore: 86, batteryScore: 87, performanceScore: 92, heatingIssue: false, longTermScore: 80, releaseYear: 2025, updateYears: 4, pros: ['Glyph 2.0 evolved', 'Flagship chip', 'Clean Android experience', 'Strong cameras for Nothing'], cons: ['Short updates vs Samsung', 'Niche identity', 'Expensive for brand'], imageUrl: '/phones/nothing-phone-3.jpg', backImageUrl: '/phones/nothing-phone-3-back.jpg' },
  { id: 'nothing-phone-3a-lite', name: 'Nothing Phone 3a Lite', brand: 'Nothing', price: 24999, processor: 'Snapdragon 6s Gen 3', cameraScore: 72, batteryScore: 85, performanceScore: 74, heatingIssue: false, longTermScore: 72, releaseYear: 2025, updateYears: 3, pros: ['Budget Nothing experience', 'Glyph interface', 'Clean Android', 'Solid build'], cons: ['Entry chip', 'Average camera', 'Short updates'], imageUrl: '/phones/nothing-phone-3a-lite.jpg', backImageUrl: '/phones/nothing-phone-3a-lite-back.jpg' },
  { id: 'nothing-phone-2a-plus', name: 'Nothing Phone 2a Plus', brand: 'Nothing', price: 27999, processor: 'Dimensity 7350 Pro', cameraScore: 78, batteryScore: 86, performanceScore: 82, heatingIssue: false, longTermScore: 76, releaseYear: 2024, updateYears: 3, pros: ['Upgraded performance', 'Glyph lights', 'Clean software', 'Good display'], cons: ['Only 3 years updates', 'Camera just average', 'No flagship chip'], imageUrl: '/phones/nothing-phone-2a-plus.jpg', backImageUrl: '/phones/nothing-phone-2a-plus-back.jpg' },
  { id: 'nothing-phone-2a', name: 'Nothing Phone 2a', brand: 'Nothing', price: 23999, processor: 'Dimensity 7200 Pro', cameraScore: 76, batteryScore: 85, performanceScore: 80, heatingIssue: false, longTermScore: 74, releaseYear: 2024, updateYears: 3, pros: ['Best value Nothing phone', 'Glyph interface', 'Clean Android', 'Good battery'], cons: ['Mid-range chip', 'Average camera', 'Short updates'], imageUrl: '/phones/nothing-phone-2a.jpg', backImageUrl: '/phones/nothing-phone-2a-back.jpg' },
  { id: 'nothing-phone-1', name: 'Nothing Phone 1', brand: 'Nothing', price: 16999, processor: 'Snapdragon 778G+', cameraScore: 72, batteryScore: 82, performanceScore: 76, heatingIssue: false, longTermScore: 65, releaseYear: 2022, updateYears: 3, pros: ['Original Glyph pioneer', 'Clean software', 'Decent mid-range', 'Iconic design'], cons: ['Old chip now', 'Camera dated', 'No more updates soon'], imageUrl: '/phones/nothing-phone-1.jpg', backImageUrl: '/phones/nothing-phone-1-back.jpg' }
]




